# Lectures 19-21


__Point of this section:__ Recall that lists _cannot_ go in sets, or be keys in dictionaries (since lists are mutable). 

We will see that searching a set is very fast compared to searching a tuple or a list. Searching for keys in a dictionary is also very fast.

In [1]:
r = range(0,10**7,5)
mylist = list(r)
mytuple = tuple(r)
myset = set(r)

In [2]:
0 in mylist

True

In [3]:
1 in mylist

False

In [4]:
5 in mylist

True

Now, we'll search each of these data types for a certain number and time how long it takes. We can do this using something called a _Jupyter magic_. These are functions that work because we are in Jupyter notebook. They are not native to python.

In [5]:
%%timeit #Example of a Jupyter magic
0 in mytuple

33.5 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Recall that ns (nanoseconds) means $10^{-9}$ seconds. Super fast, huh?

In [6]:
%%timeit
0 in mylist

41.4 ns ± 6.02 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


This result looks pretty similar to the one for `mytuple`...

In [7]:
%%timeit
0 in myset

51.4 ns ± 9.33 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


What's going on here? Searching for 0 in `myset` took longer than for `mytuple` and `mylist`. What's happening is that 0 is the first element of all of these objects, so our search time is not a good representative of what will typically happen.

To get a better idea of the speed differences, we should try a "worst-case-scenario": let's search for something that's not in our list/tuple/set at all! Let's repeat all of these computations, but search for 1 instead.

In [8]:
%%timeit
1 in mytuple

26.5 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Here, ms (millisecond) means $10^{-3}$ seconds.

In [9]:
%%timeit
1 in mylist

31.6 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Here, $\mu s$ (microseconds) means $10^{-6}$ seconds.

In [10]:
%%timeit 
1 in myset

47.4 ns ± 2.03 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


## Alternating List
__Big Goal:__ Write a function that creates a length $n$ list of alternating 3s and 7s: `[3,7,3,7,...]`

### Constant List
__Mini Goal:__ Write a function that takes as input a natural number $n$, and as output returns a length $n$ list `[3,3,3,3...]`

In this section, we'll learn the basic syntax for writing functions in python.

In [11]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

Notice in the for-loop above, the variable `i` is never used in the loop. When this is the case, people will often use `_` as the variable instead, to indicate that it won't show up.

Let's try running our function.

In [12]:
print(f(4))

None


Notice there is no error, but there's also no output! Here's how we can specify the output. The code below still has a small issue.

In [13]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [14]:
f(10)

[3]

In [15]:
f(5)

[3]

What's going on here? Notice that because `return` is in the for-loop, we exit the function right after we append one 3 to `mylist`. To fix this, we have to move `return` outside of the for-loop.

In [16]:
def f(n):
    mylist = []
    for _ in range(n):   #underscore is useful when you don't use the variable in the loop
        mylist.append(3)
    return mylist

f(8)

[3, 3, 3, 3, 3, 3, 3, 3]

Finally, our function should work as expected.

In [17]:
f(3)

[3, 3, 3]

In [18]:
f(4)

[3, 3, 3, 3]

In [19]:
f(0)

[]

In [20]:
f(7)

[3, 3, 3, 3, 3, 3, 3]

Notice I ran `f(7)` above. Within the function `n` was set to 7. But `n` does not persist outside of the function.

In [21]:
n

NameError: name 'n' is not defined

What if we define `n` outside of the function?

In [22]:
n = 100
f(4)

[3, 3, 3, 3]

In [23]:
n

100

The above shows us that input variables are locally defined.

### Alternating List - Version 1

Let's copy-paste our constant function. We will make use of it here.

In [24]:
def constant(n):
    mylist = []
    for _ in range(n):
        mylist.append(3)
    return mylist

Now we try to write our alternating function. Our strategy is to first create a length $n$ list of 3s, and then change the odd indices to be 7s.

In [25]:
def alt1(n):
    mylist = constant(n)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

In [26]:
#mylist[1::2] = 7   #notation like this doesn't work for python lists. Need python arrays (later in this page)

Note that calling `constant(n)` inside of `alt1(n)`, has many advantages. For one, it's less work than copying and pasting. Even further, if we realized we need to change `constant(n)`, we only need to do it in one place. If we copy-paste to multiple locations, we have to update the code in all of these locations.

In [27]:
alt1(4)

[3, 7, 3, 7]

In [28]:
alt1(5)

[3, 7, 3, 7, 3]

In [29]:
alt1(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

The nice thing about `alt1(n)` is that we didn't need to check if indices of `mylist` were even or odd.

### Alternating List - Version 2

Let's see another way of writing a function that does the same thing as `alt1(n)`. The strategy this time is to check whether an index is even or odd.

In [30]:
def alt2(n):
    mylist = []
    for i in range(n):
        if i%2 == 0:     #i mod 2 equals 0 is the same as saying i has no remainder when we divide by 2. This means i is even.
            mylist.append(3)
        else:
            mylist.append(7)
    return mylist

In [31]:
def cycle_three(n):  #gives lists of the form [3, 7, 6, 3, 7, 6, ... ]
    mylist = []
    for i in range(n): #i represents the index of mylist
        if i%3 == 0:  #if i divided by 3 has zero for a remainder. Same as if i were a multiple of 3.
            mylist.append(3)
        elif i%3 == 1:
            mylist.append(7)
        else:
            mylist.append(6)
    return mylist

Notice how we didn't need to specify an `elif`. This is because an integer only has two possible remainders when we divide by 2. If the remainder is not 0, it must be 1.

Recall: We can use `m%n` to check the remainder of `m` divded by `n`.

In [32]:
5%2

1

In [33]:
7%2

1

In [34]:
4%2

0

__Observe:__ even numbers have a remainder of 0 when we divide by 2, and odd numbers have a remainder of 1 when we divide by 2.

Now, we test `alt2(n)` and `cycle_three(n)` a few times.

In [35]:
alt2(20)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [36]:
alt2(6)

[3, 7, 3, 7, 3, 7]

In [37]:
cycle_three(4)

[3, 7, 6, 3]

In [38]:
cycle_three(20)

[3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7]

### Alternating List - Version 3

For this version of the alternating function, we will use NumPy. NumPy is one of the most important python libraries, and should remind you a lot of MATLAB. Let's start by seeing how we can import it into this notebook.

In [39]:
import numpy as np

__Note:__ 
* `np` is a standard abbreviation, and you should not use anything else when importing numpy.

* Notice that when I evaluate the cell with the import statement there is no error. If you get an error at this step, it means that NumPy is not installed on your computer. (However, Anaconda's regular installation always comes with NumPy)

In [40]:
np.zeros((3,4)) #notice the dimensions are in a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

The data type `numpy.ndarray` should make you think $n$-dimensional array.

In [41]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
np.zeros((3,4)).shape

(3, 4)

In [43]:
A = np.zeros((3,5))
type(A)

numpy.ndarray

Notice that the following doesn't give a square array, which is what we would expect in MATLAB.

In [44]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros(7).shape

(7,)

In [46]:
np.zeros(7).ndim

1

In [47]:
np.zeros((1,7))

array([[0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros((1,7)).shape

(1, 7)

In [49]:
np.zeros((1,7)).ndim

2

Notice that the entires of my array are floating point numbers, not integers.

In [50]:
type(np.zeros(7)[0])

numpy.float64

In [51]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [52]:
np.zeros(7,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0], dtype=int64)

Now let's try to use NumPy to write another version of our alternating function. We start with creating a constant array.

In [53]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64)
    return A

In [54]:
alt3(4)

array([0, 0, 0, 0], dtype=int64)

In [55]:
alt3(4).shape

(4,)

In [56]:
alt3(5) + 3    #This trick is known as broadcasting, and it works in Matlab. Does not work for lists in Python, but works for ndarrays

array([3, 3, 3, 3, 3], dtype=int64)

In [57]:
#constant with all threes
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    return A

We might be tempted to think this same strategy works with lists. But this is not the case!

In [58]:
mylist = [0,0,0]

In [59]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [60]:
mylist + [3]

[0, 0, 0, 3]

Now, let's update our function so that the odd entries are 7s.

In [61]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7   #This also works in Matlab! We broadcasted assignment across a slice of an array. Python lists cannot do this, but ndarrays can
    return A

Now, we test our function a few times before making some last comments.

In [62]:
alt3(10)

array([3, 7, 3, 7, 3, 7, 3, 7, 3, 7], dtype=int64)

In [63]:
alt3(4)

array([3, 7, 3, 7], dtype=int64)

Notice how `A[1::2] = 7` worked as we would expect in MATLAB. This will not work with just lists.

In [64]:
mylist = [3,1,4,1,5,9]

In [65]:
mylist[::2]  #can call a slice of a list

[3, 4, 5]

What if I wanted to set all of these entries to -17?

In [66]:
mylist[::2] = -17

TypeError: must assign iterable to extended slice

What's going wrong here is that I need to assign `mylist[::2]` to a list with the same number of elements.

In [67]:
mylist[::2] = [-17,-17,-17]
mylist

[-17, 1, -17, 1, -17, 9]

The point is that this is a lot more complicated than using NumPy! Notice how we needed to know exactly how long `mylist[::2]` is. 

NumPy arrays are capable of Broadcasting, which is the way Python operations and assignment work with arrays of differing sizes (similar to MATLAB).

### Timing Alternating List Strategies
__Upshot:__ NumPy will be much faster than base python!

Let's start by copy-pasting our code for `alt3(n)`. Remember, this is the code that used NumPy.

In [68]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return A

To get a more accurate time comparison, we're going to write another function `alt3_mimic(n)` which uses lists and is meant to mimic how `alt3(n)` is structured:
* Create a length n list of all 3s.
* Change all of the odd indices to be 7s.

In [69]:
def alt3_mimic(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

Let's run a couple of test cases.

In [70]:
alt3_mimic(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [71]:
alt3_mimic(5)

[3, 7, 3, 7, 3]

Recall, we can use the Jupyter magic `%%timeit` to time how long it takes a block of code to run.

In [72]:
%%timeit 
alt3_mimic(10)

1.22 μs ± 91.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


We will now see a timing method that gives just the time, without all of the extra information given by `%%timeit`.

In [73]:
#comes with python, no installation
import time 

In [74]:
time.time()

1741123635.2274613

This gives how much time has elapsed since the beginning of Unix time (computer time): January 1st, 1970.

In [75]:
time.time()

1741123635.2373369

Notice, if I take the difference between these two numbers, I can calculate how long I was talking for :)

Here's how we can compute the time of some computation without using Jupyter magics.

In [76]:
start = time.time()
alt3_mimic(10**5)
end = time.time()
t = end - start

In [77]:
t

0.0

__Mini Goal:__ Use a while loop to find $n$ such that `alt3_mimic(n)` takes more than 5 seconds to run.

In [78]:
t = 0
n = 100
while t < 5:
    n = 2*n
    start = time.time()
    alt3_mimic(n)
    end = time.time()
    t = end-start

In [79]:
t

10.038664817810059

In [80]:
n

104857600

Notice: it wouldn't make sense for us to increment `n = 2*n` at the end of the while-loop. Why?

Now, let's see how much faster `alt3(n)`, our NumPy version, can run for the same `n`.

In [81]:
print(n)
start = time.time()
alt3(n)
end = time.time()
t = end-start
print(t)

104857600


0.5712285041809082


Appreciate the difference! What took base python (lists) more than 5 seconds, took NumPy about $\frac{1}{3}$ of a second.

Let's now keep our NumPy code, but return a list at the very end. 

In [82]:
def alt3_list(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return list(A)   #Convert numpy array to a list

In [83]:
print(n)
start = time.time()
alt3_list(n)
end = time.time()
t = end-start
print(t)

104857600


6.96020245552063


What made `alt3_list(n)` so slow? It was the fact that we converted `A` to a list.

What if we used a for-loop instead of slicing in our NumPy function?

In [84]:
def alt3_loop(n):
    A = np.zeros(n,dtype=np.int64) + 3
    for i in range(1,n,2):
        A[i] = 7
    return A

In [85]:
print(n)
start = time.time()
alt3_loop(n)
end = time.time()
t = end-start
print(t)

104857600


6.876494884490967


__Takeaway:__ Using for-loops is very slow! Avoid them when you can :)

## More numpy built-in methods

Very similar to `linspace` in Matlab

In [86]:
import numpy as np
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

Note: unlike other Python methods, the endpoint is included by default.

In [87]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

The operation we see below also works in Matlab. It is one example of what's known as broadcasting.

In [88]:
np.zeros((3,5)) + 7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

We can convert the floating point to an integer using the `dtype` keyword

In [89]:
np.ones((3,5), dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [90]:
np.ones((3,5), dtype=np.int64)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int64)

* Construct the $2 \times 5$ matrix 

$
\begin{pmatrix}
2 & 5 & 8 & 11 & 14 \\
17 & 20 & 23 & 26 & 29
\end{pmatrix}
$

__Method 1:__ We notice that the difference between consecutive elements is 3. We'll use a for-loop to create this array.

In [91]:
import numpy as np

In [92]:
arr=np.zeros((2,5), dtype=int)
arrshape = arr.shape
print(arrshape[0])
print(arrshape[1])
for row in range(arrshape[0]):
    for col in range(arrshape[1]):
        arr[row,col] = 2 + 3*col + 15*row
arr

2
5


array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

__Method 2:__ use `np.arange` to get the pattern, then a new method, `reshape`

`np.arange` is the numpy array version of `range`

In [93]:
print([0, 1, 2, 3])  #list
np.array([0, 1, 2, 3]) #numpy array

[0, 1, 2, 3]


array([0, 1, 2, 3])

In [94]:
print(range(4))
np.arange(4)  #Still computationally efficient, even though all elements are listed

range(0, 4)


array([0, 1, 2, 3])

In [95]:
arr2=np.arange(2,30,3)
print(arr2)

[ 2  5  8 11 14 17 20 23 26 29]


In [96]:
arr2.reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

This can also be done in one line!

In [97]:
np.arange(2,30,3).reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [98]:
np.arange(2,30,3).reshape((3,2))

ValueError: cannot reshape array of size 10 into shape (3,2)

In [99]:
np.arange(2,30,3).reshape((-1,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

The $-1$ used in reshape means "give me any dimension that forces this to work".

In [100]:
np.arange(2,30,3).reshape((2,-1))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [101]:
np.arange(2,30,3).reshape((-1,2))

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])