# Lectures 23-24 from FA24

In [2]:
import numpy as np

## An exact probability 

__Goal:__ Compute the exact probability of the question from last time. 

<blockquote>If you roll 4 distinct 6-sided dice, what is the probability that the largest value is 5?</blockquote>

I claim that we can compute an exact value. Notice that there are only 1296 total outcomes. We can definitely iterate through all of them.

In [52]:
6**4

1296

The idea now is that we'll list out all of the possible outcomes, and count how many of them have 5 as the largest number. The first method is what you might think to do first, and then I'll show you a more elegant way.

In [60]:
all_dice = []

for i in range(1,7):
    for j in range(1,7):
        for k in range(1,7):
            for l in range(1,7):
                all_dice.append((i,j,k,l))

In [62]:
len(all_dice)

1296

Try to predict what this will look like before we run the code. It's good practice for iterating through nested for-loops.

In [64]:
all_dice[:10] #header of first 10 values

[(1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 1, 4),
 (1, 1, 1, 5),
 (1, 1, 1, 6),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3),
 (1, 1, 2, 4)]

Some things that are not-so-great about this for-loop method:

* Time efficiency 
* There's a lot of repetition. There's the concept of DRY (Don't Repeat Yourself) code. Notice that we've repeated ourselves a lot! 
    * Any time you see yourself writing the same line of code over and over again, there's usually a better way to do it.

In [66]:
from itertools import product

In [68]:
help(product)

Help on class product in module itertools:

class product(builtins.object)
 |  product(*iterables, repeat=1) --> product object
 |
 |  Cartesian product of input iterables.  Equivalent to nested for-loops.
 |
 |  For example, product(A, B) returns the same as:  ((x,y) for x in A for y in B).
 |  The leftmost iterators are in the outermost for-loop, so the output tuples
 |  cycle in a manner similar to an odometer (with the rightmost element changing
 |  on every iteration).
 |
 |  To compute the product of an iterable with itself, specify the number
 |  of repetitions with the optional repeat keyword argument. For example,
 |  product(A, repeat=4) means the same as product(A, A, A, A).
 |
 |  product('ab', range(3)) --> ('a',0) ('a',1) ('a',2) ('b',0) ('b',1) ('b',2)
 |  product((0,1), (0,1), (0,1)) --> (0,0,0) (0,0,1) (0,1,0) (0,1,1) (1,0,0) ...
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Impl

In [70]:
#let's start with repeat=2 just to see what's going on
list(product(range(1,7),repeat=2))   #same as direct or Cartesian product of A x A, from Math 13

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [72]:
temp_list = list(product(range(1,7),repeat=4))

In [ ]:
%%time
temp_list = list(product(range(1,7),repeat=20))

Let's see a few more examples with `product` before we go in and compute the probability.

In [74]:
list(product(["a","b","c"],[5,6])) #cartesian product

[('a', 5), ('a', 6), ('b', 5), ('b', 6), ('c', 5), ('c', 6)]

Notice the use of repeat in the following example.

In [78]:
list(product(["a","b","c"],["a","b","c"],["a","b","c"]))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [80]:
list(product(["a","b","c"],repeat=3))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [82]:
for x in ["a","b","c"]:
    print(x)

a
b
c


In [84]:
len(temp_list)

1296

In [86]:
arr = np.array(temp_list)

In [88]:
arr[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       [1, 1, 1, 4],
       [1, 1, 1, 5],
       [1, 1, 1, 6],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 1, 2, 3],
       [1, 1, 2, 4]])

In [90]:
arr.shape

(1296, 4)

In [94]:
#here is our exact probability
(arr.max(axis = 1) == 5).mean()

0.2847222222222222

In [96]:
#Mathematically
(5/6)**4 - (4/6)**4

0.2847222222222223

## `any` and `all` 

In [159]:
import numpy as np

In [161]:
rng = np.random.default_rng()

* Make a 100 row, 4 column NumPy array of random real numbers between 0 and 1.

In [100]:
rng.random()

0.3776381831248814

In [8]:
arr = rng.random(size=(100,4))

In [10]:
 arr[:7]  #just first 7 rows (rows 0 through 6), instead of all 100 rows

array([[0.04427778, 0.63000896, 0.20577815, 0.52670275],
       [0.94707787, 0.7410204 , 0.40452408, 0.65797918],
       [0.92314818, 0.02240709, 0.39447423, 0.11648477],
       [0.42102449, 0.09855248, 0.86815752, 0.71312652],
       [0.56506532, 0.94631355, 0.72213086, 0.94365986],
       [0.59119977, 0.09131657, 0.72705826, 0.13706572],
       [0.25708519, 0.17038613, 0.20805631, 0.45832554]])

* Find the subarray containing all rows in which at least one number is greater than 0.9

Let's practice with the first 7 rows, and then we'll do the whole array.

In [12]:
arr[:7] > 0.9

array([[False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [14]:
(arr[:7] > 0.9).any()

True

In [16]:
(arr[:7] > 0.9).any(axis=1)

array([False,  True,  True, False,  True, False, False])

In [18]:
(arr[:7] > 0.9).any(axis=1).sum()

3

Here's an example of boolean indexing, where we keep only the rows where at least one element is larger than 0.9.

In [20]:
arr[:7][(arr[:7] > 0.9).any(axis=1)]

array([[0.94707787, 0.7410204 , 0.40452408, 0.65797918],
       [0.92314818, 0.02240709, 0.39447423, 0.11648477],
       [0.56506532, 0.94631355, 0.72213086, 0.94365986]])

Now for the whole array, and not just the first 7 rows.

In [22]:
comparison = arr > 0.9
comp_rows = comparison.any(axis=1)
arr[comp_rows]

#boolean_rows = (arr > 0.9).any(axis=1)
#arr[boolean_rows]

array([[0.94707787, 0.7410204 , 0.40452408, 0.65797918],
       [0.92314818, 0.02240709, 0.39447423, 0.11648477],
       [0.56506532, 0.94631355, 0.72213086, 0.94365986],
       [0.81937934, 0.99691556, 0.27906117, 0.06812475],
       [0.9798922 , 0.95757726, 0.46953082, 0.50108233],
       [0.92663719, 0.31017944, 0.2864874 , 0.62139566],
       [0.60909576, 0.94406793, 0.66308408, 0.13402301],
       [0.69390911, 0.55791667, 0.69594257, 0.94990126],
       [0.92248966, 0.80932234, 0.72402302, 0.65972763],
       [0.04584555, 0.1578322 , 0.13186831, 0.98356084],
       [0.11157516, 0.0229495 , 0.90555635, 0.71114597],
       [0.92977074, 0.21825508, 0.3227355 , 0.76422281],
       [0.99989026, 0.6181912 , 0.42047595, 0.60634374],
       [0.91225801, 0.82118314, 0.7519146 , 0.10284217],
       [0.8025577 , 0.98053439, 0.20731187, 0.38953656],
       [0.14276482, 0.16904681, 0.97669687, 0.12920872],
       [0.00152987, 0.90840349, 0.12780888, 0.5647805 ],
       [0.33011484, 0.17096778,

* Find the subarray containing all rows in which no numbers are between 0.4 and 0.6.

In [163]:
arr = rng.random(size=(100,4))

In [165]:
arr[:7]

array([[0.19751648, 0.02028313, 0.47407592, 0.52697752],
       [0.145751  , 0.36951586, 0.33129647, 0.67104014],
       [0.8490129 , 0.42459474, 0.45046837, 0.7318382 ],
       [0.41178083, 0.46413365, 0.60745129, 0.71535763],
       [0.31954088, 0.31536108, 0.17807527, 0.34794251],
       [0.86638948, 0.36735755, 0.14092008, 0.37014619],
       [0.20125787, 0.54386114, 0.36907974, 0.84896809]])

In [167]:
((arr[:7] < 0.4)|(arr[:7] > 0.6))

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [169]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all()

False

In [171]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)

array([False,  True, False, False,  True,  True, False])

In [173]:
arr[:7][((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)]

array([[0.145751  , 0.36951586, 0.33129647, 0.67104014],
       [0.31954088, 0.31536108, 0.17807527, 0.34794251],
       [0.86638948, 0.36735755, 0.14092008, 0.37014619]])

In [175]:
((arr < 0.4)|(arr > 0.6)).all(axis=1).shape

(100,)

To get the full subarray

In [177]:
arr[((arr < 0.4)|(arr > 0.6)).all(axis=1)]

array([[0.145751  , 0.36951586, 0.33129647, 0.67104014],
       [0.31954088, 0.31536108, 0.17807527, 0.34794251],
       [0.86638948, 0.36735755, 0.14092008, 0.37014619],
       [0.65667426, 0.67074816, 0.93442592, 0.29571087],
       [0.93944731, 0.91272001, 0.65020332, 0.86083679],
       [0.75415533, 0.27251741, 0.2513797 , 0.80973447],
       [0.00547891, 0.25950361, 0.70479242, 0.82591293],
       [0.85145813, 0.08065407, 0.7806936 , 0.09747803],
       [0.16630757, 0.92579764, 0.19557505, 0.77925279],
       [0.28429194, 0.86177633, 0.79925986, 0.06867197],
       [0.34789399, 0.62560158, 0.15045884, 0.30224264],
       [0.67897079, 0.13921175, 0.91796386, 0.79405301],
       [0.69266229, 0.98307253, 0.7954691 , 0.69237045],
       [0.61100538, 0.30667161, 0.31443351, 0.34049789],
       [0.07252753, 0.78483624, 0.07277006, 0.81988288],
       [0.1896075 , 0.6377413 , 0.26640999, 0.83873865],
       [0.20975199, 0.19500965, 0.86387026, 0.6761449 ],
       [0.39183499, 0.3873557 ,

## Binary to Decimal

$$
\begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 1 & 1 & 1
\end{pmatrix} \mapsto
\begin{pmatrix}
10 \\
4 \\
15
\end{pmatrix}
$$

__Goal:__ Write a function `to_bin` which takes as input an $m \times n$ NumPy array of 0s and 1s, and as output returns the corresponding base 10 integers (we think of each row as representing the binary digits of an integer).

Let's talk a little bit about converting between binary and decimal. Jessica will cover more, but here are the basics.

Someone give me a number between 100 and 1000: 170. 
* In decimal, we use the digits 0-9 and multiply with powers of 10.

$170 = 100 + 70 + 0 = 1 \times 10^2 + 7 \times 10^1 + 0 \times 10^0$

$543 = 5 \times 10^2 + 4 \times 10^1 + 3 \times 10^0$

* In binary, we use digits 0-1 and multiply with powers of 2.

$1010 = 1 \times 2^3 + 0 \times 2^2 + 1 \times 2^1 + 0 \times 2^0 = 8 + 2 = 10$ 

Let's try to get all of our ideas together, and then write the function.

In [179]:
arr = rng.integers(2,size=(10,4))

In [181]:
arr

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

In [183]:
#tuple unpacking
m,n = arr.shape

In [185]:
arr.shape

(10, 4)

In [187]:
m

10

In [189]:
n

4

These are the powers of 2 that I will be taking.

In [191]:
np.arange(n-1,-1,-1)   #get the exponents first. start at n-1 = 3, stop before -1, and count down -1

array([3, 2, 1, 0])

In [193]:
2**np.arange(n-1,-1,-1)

array([8, 4, 2, 1], dtype=int32)

In [197]:
arr

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

In [199]:
arr*2**np.arange(n-1,-1,-1)    #Broadcast [8, 4, 2, 1] across all rows of arr, with multiplication

array([[0, 0, 0, 1],
       [8, 4, 2, 0],
       [8, 0, 2, 0],
       [8, 4, 0, 0],
       [8, 4, 2, 0],
       [8, 0, 0, 1],
       [8, 4, 0, 1],
       [8, 4, 2, 1],
       [0, 0, 0, 1],
       [0, 0, 2, 0]], dtype=int64)

In [201]:
(arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

array([ 1, 14, 10, 12, 14,  9, 13, 15,  1,  2], dtype=int64)

In [203]:
def to_bin(arr):
    _,n = arr.shape   #Note the first part of the shape goes unused, so we can use _ to avoid storing the variable
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [205]:
to_bin(arr)

array([ 1, 14, 10, 12, 14,  9, 13, 15,  1,  2], dtype=int64)

In [211]:
to_bin(np.array([[1,1],[1,0]]))

array([3, 2])

## Raising Errors 

__Goal:__ Edit the `to_bin` function so that it raises an error if the input is not a NumPy array and also if an entry is not 0 or 1.

In [215]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [217]:
arr

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

In [219]:
type(arr)

numpy.ndarray

You might be tempted to check `type(arr) == np.ndarray`, but this is something you'll almost never see in practice.

Here's how we check instead:

In [221]:
isinstance(arr,np.ndarray)

True

In [229]:
isinstance(list(arr),np.ndarray)

False

In [239]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [241]:
to_bin("Hello")

TypeError: Input should be a NumPy array.

In [243]:
to_bin(arr)

array([ 1, 14, 10, 12, 14,  9, 13, 15,  1,  2], dtype=int64)

In [245]:
to_bin([1,2,3])

TypeError: Input should be a NumPy array.

Now let's check if each entry is 0 or 1.

In [248]:
arr == 0

array([[ True,  True,  True, False],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [250]:
arr == 1

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

In [252]:
((arr == 0) | (arr == 1))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [254]:
#Check if every entry is 0 or 1
((arr == 0) | (arr == 1)).all()

True

In [256]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    if not ((arr == 0) | (arr == 1)).all():
        raise ValueError("All entries should be 0 or 1.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

Now, let's try to test our function. I'm going to make a subtle mistake below. I want to make an array that's not all 0s/1s.

In [258]:
arr
arr2 = arr

In [260]:
arr2[5,2] = 6

In [262]:
arr2

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 6, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

In [264]:
to_bin(arr2)

ValueError: All entries should be 0 or 1.

This is good, the function is behaving exactly as we would expect. However, notice that the following also throws an error.

In [266]:
to_bin(arr)

ValueError: All entries should be 0 or 1.

In [268]:
arr

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 6, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

The basic idea here is that `arr` and `arr2` point to the same object in memory. When one gets changed, so does the other. (Don't worry so much about why this happens, unless you're interested :))

__Upshot:__ If I want to change values, I need to make a copy.

In [270]:
arr3 = arr2.copy()

In [272]:
arr3[6,1::2] = 99

In [274]:
arr3

array([[ 0,  0,  0,  1],
       [ 1,  1,  1,  0],
       [ 1,  0,  1,  0],
       [ 1,  1,  0,  0],
       [ 1,  1,  1,  0],
       [ 1,  0,  6,  1],
       [ 1, 99,  0, 99],
       [ 1,  1,  1,  1],
       [ 0,  0,  0,  1],
       [ 0,  0,  1,  0]], dtype=int64)

In [276]:
arr2

array([[0, 0, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 6, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int64)

***

The next few portions of lecture will be about something called "Pythonic Code". This more or less refers to things that are unique-ish to Python.

## List Comprehension – Pythonic Code 1 

__Words of Advice:__ If you're ever confused about how to write something with list comprehension, think about how you'd write it with a for-loop, and then convert it.

__Benefit:__ Code written with list comprehension is usually more readable than for-loops, but don't expect it to run any faster.

* Length 8 list of all 7s.

Let's think about how we'd do this with for-loops.

In [39]:
mylist = []
for i in range(8):
    mylist.append(7)
mylist

[7, 7, 7, 7, 7, 7, 7, 7]

In [41]:
[7 for _ in range(8)]

[7, 7, 7, 7, 7, 7, 7, 7]

* Let `mylist = [-1,4,2,3,-10,2,4]`. Square each element in `mylist`.

In [44]:
mylist = [-1,4,2,3,-10,2,4]

In [46]:
[x for x in mylist]

[-1, 4, 2, 3, -10, 2, 4]

In [48]:
[x**2 for x in mylist]

[1, 16, 4, 9, 100, 4, 16]

* Get the sublist of `mylist` containing only even numbers.

In [151]:
[x for x in mylist if x%2 == 0]

[4, 2, -10, 2, 4]

In [50]:
extralist = []
for x in mylist:
    if x%2 == 0:
        extralist.append(x)
print(extralist)

[4, 2, -10, 2, 4]


* Replace each negative number in `mylist` with zero.

Notice now the syntax difference!

In [52]:
mylist

[-1, 4, 2, 3, -10, 2, 4]

In [130]:
[x if x >= 0 else 0 for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [132]:
[0 if x < 0 else x for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

* Make the length 8 list of lists `[[0,1,2],[0,1,2],...,[0,1,2]]`.

In [133]:
[[0,1,2] for _ in range(8)]

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [134]:
len([[0,1,2] for _ in range(8)])

8

* Make the length 24 list `[0,1,2,0,1,2,0,1,2...]`

Let's try this one with a for-loop first, and then see how we could do it with list comprehension.

In [137]:
mylist2 = []
for i in range(8):
    for j in range(3):
        mylist2.append(j)
mylist2

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [138]:
len(mylist2)

24

In [139]:
[j for i in range(8) for j in range(3)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

* Capitalize each word in the catalogue description of Math 9:


Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.

In [54]:
s = '''Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.'''

In [56]:
print(s)

Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.


In [58]:
#Notice this goes character by character
[c for c in s]

['I',
 'n',
 't',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 ' ',
 't',
 'o',
 ' ',
 'c',
 'o',
 'm',
 'p',
 'u',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'u',
 's',
 'i',
 'n',
 'g',
 ' ',
 'M',
 'a',
 't',
 'l',
 'a',
 'b',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '.',
 ' ',
 'R',
 'e',
 'p',
 'r',
 'e',
 's',
 'e',
 'n',
 't',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'o',
 'f',
 ' ',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'e',
 'c',
 'i',
 's',
 'i',
 'o',
 'n',
 ',',
 ' ',
 'i',
 'n',
 'p',
 'u',
 't',
 '/',
 'o',
 'u',
 't',
 'p',
 'u',
 't',
 ',',
 ' ',
 'f',
 'u',
 'n',
 'c',
 't',
 'i',
 'o',
 'n',
 's',
 ',',
 ' ',
 'c',
 'u',
 's',
 't',
 'o',
 'm',
 ' ',
 'd',
 'a',
 't',
 'a',
 ' ',
 't',
 'y',
 'p',
 'e',
 's',
 ',',
 ' ',
 't',
 'e',
 's',
 't',
 'i',
 'n',
 'g',
 '/',
 'd',
 'e',
 'b',
 'u',
 'g',
 'g',
 'i'

In [60]:
#This splits the string s at the spaces
wordlist = s.split()
print(wordlist)

['Introduction', 'to', 'computers', 'and', 'programming', 'using', 'Matlab', 'and', 'Python.', 'Representation', 'of', 'numbers', 'and', 'precision,', 'input/output,', 'functions,', 'custom', 'data', 'types,', 'testing/debugging,', 'reading', 'exceptions,', 'plotting', 'data,', 'numerical', 'differentiation,', 'basics', 'of', 'algorithms.', 'Analysis', 'of', 'random', 'processes', 'using', 'computer', 'simulations.']


In [64]:
caplist = [c.capitalize() for c in wordlist]

print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [66]:
caplist = []

for c in wordlist:
    caplist.append(c.capitalize())

In [68]:
print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


This is a list of capitalized words, the last thing to do is put it back together.

In [86]:
s2 = ' '.join(caplist)

In [88]:
s2

'Introduction To Computers And Programming Using Matlab And Python. Representation Of Numbers And Precision, Input/output, Functions, Custom Data Types, Testing/debugging, Reading Exceptions, Plotting Data, Numerical Differentiation, Basics Of Algorithms. Analysis Of Random Processes Using Computer Simulations.'

In [90]:
type(s2)

str