In [1]:
import numpy as np

In [2]:
np.random.randint(0,39,size=10)

array([ 7,  9, 36, 26,  9, 32, 18, 21, 38,  4])

In [3]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [4]:
rng = np.random.default_rng()

In [5]:
type(rng)

numpy.random._generator.Generator

In [6]:
arr = rng.integers(0,39,size=10)

In [7]:
arr

array([31,  4, 25,  4, 31, 29,  4,  6, 11, 20], dtype=int64)

In [8]:
rng.choice(arr,size=5)

array([ 6,  4, 31, 31,  4], dtype=int64)

In [9]:
arr2 = np.arange(0,100,3)
print(arr2)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [10]:
rng.choice(arr2,size=5)

array([51, 42, 15, 78,  6])

In [11]:
rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [12]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)

    Return random floats in the half-open interval [0.0, 1.0).

    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` use `uniform`
    or multiply the output of `random` by ``(b - a)`` and add ``a``::

        (b - a) * random() + a

    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
 

In [13]:
#3x5 array of random reals between 0 and 1
rng.random((3,5))

array([[0.63639938, 0.14321158, 0.50181092, 0.15542208, 0.06097109],
       [0.35053398, 0.12103873, 0.79440398, 0.23408501, 0.41750954],
       [0.25299425, 0.48110359, 0.29666487, 0.29270087, 0.36098552]])

In [14]:
#Mult. by 5 to stretch to correct length
#subtract 1 to shift to correct interval.
5*rng.random((3,5))-1

array([[-0.65811269,  0.85614464, -0.43462575,  1.83277562,  0.31214265],
       [ 0.6675575 , -0.35339963,  1.58531215, -0.81830605,  0.1382895 ],
       [ 3.99054774, -0.16231391, -0.20045659,  2.6502247 ,  2.77133626]])

In [15]:
help(rng.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or tuple of ints,

In [16]:
rng.normal(2,0.1,size=10)

array([1.87947666, 2.09680206, 1.95516396, 1.92451908, 1.99038028,
       2.12694974, 1.91952084, 2.00872074, 1.99636867, 2.10151871])

In [17]:
import numpy as np

In [18]:
arr = np.zeros((4,4), dtype=int)
print(arr)
print()
print(np.arange(4).reshape(4,1))
arr = arr + np.arange(4).reshape(4,1)
print()
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0]
 [1]
 [2]
 [3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [19]:
arr[3,:]

array([3, 3, 3, 3])

In [20]:
arr[3]

array([3, 3, 3, 3])

In [21]:
v = arr[:,2]

In [22]:
v   #displayed horizontally because it only has one dimension in its shape

array([0, 1, 2, 3])

In [23]:
v.shape

(4,)

In [24]:
arr[3]

array([3, 3, 3, 3])

In [25]:
arr[3] = [2,10]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [26]:
arr[3] = [2,10,2,10]
arr

array([[ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [27]:
arr[0] = 5
arr

array([[ 5,  5,  5,  5],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [28]:
#Make a prediction
arr[:] = [1,3,4,7]
arr

array([[1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7]])

In [29]:
arr[:, 1] = [1,3,4,7]
arr

array([[1, 1, 4, 7],
       [1, 3, 4, 7],
       [1, 4, 4, 7],
       [1, 7, 4, 7]])

In [30]:
arr = np.zeros((4,4), dtype=int) + np.array([1,3,4,7]).reshape(4,1)
arr

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [7, 7, 7, 7]])

In [31]:
[1,3,4,7].reshape(4,1)   #lists cannot be reshaped. We need numpy arrays in order to reshape

AttributeError: 'list' object has no attribute 'reshape'

In [32]:
arr.shape

(4, 4)

In [33]:
w = np.array([1,3,4,7])

In [34]:
w.shape

(4,)

In [35]:
arr = np.zeros((5,5),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [37]:
arr[:] = np.arange(5)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [38]:
#transpose
arr = arr.T   #Transpose of an array. For a 2-dim array, swaps rows and columns.
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [39]:
np.arange(5).shape

(5,)

In [40]:
arr[:] = np.arange(5).reshape((5,1))
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [41]:
z = np.arange(5).reshape((5,1))
print(z)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [42]:
z = np.arange(5).reshape((-1,1))
print(z)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [43]:
z.shape

(5, 1)

In [44]:
arr[:] = np.arange(5).reshape((-1,1))
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [45]:
arr.reshape(-1)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [46]:
arr.reshape(-1).shape

(25,)

In [47]:
import numpy as np

In [48]:
NewArr = np.arange(1,25).reshape(4,6)
NewArr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [49]:
NewArr + [[1, 1, 11, 1, 1, 1]]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [50]:
np.array([[1, 1, 11, 1, 1, 1]]).shape

(1, 6)

In [51]:
NewArr + [1, 1, 11, 1, 1, 1]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [52]:
np.array([1, 1, 11, 1, 1, 1]).shape

(6,)

In [53]:
NewArr + [5 , 9, 0, 9]

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [54]:
NewArr + [[5 , 9, 0, 9]]

ValueError: operands could not be broadcast together with shapes (4,6) (1,4) 

In [55]:
vecbroadcast1 = np.array([[5, 9, 0, 9]]).reshape(4,1)
print(vecbroadcast1)

[[5]
 [9]
 [0]
 [9]]


In [56]:
print(NewArr)
NewArr + vecbroadcast1

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

In [57]:
NewArr +  [[5], [9], [0], [9]]

array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

In [58]:
a = np.arange(5).reshape(5,1)
b = np.arange(6).reshape(1,6)

In [59]:
c = np.arange(10,16)
c.shape

(6,)

In [60]:
d = 15

In [61]:
print(TheArr + a)
print(TheArr*a)

NameError: name 'TheArr' is not defined

In [62]:
print(TheArr + b)
print(TheArr*b)

NameError: name 'TheArr' is not defined

In [63]:
TheArr + c

NameError: name 'TheArr' is not defined

In [64]:
import numpy as np

In [65]:
rng = np.random.default_rng()
n = 20
arr = rng.integers(-50,51, size=n)
mylist = list(arr)

In [66]:
mylist

[-1,
 46,
 -11,
 -34,
 7,
 -5,
 38,
 -39,
 6,
 -26,
 -47,
 -36,
 21,
 19,
 13,
 -37,
 -21,
 35,
 3,
 12]

In [67]:
mylist < 10    #cannot compare an entire list to an integer. But does this work for an array?

TypeError: '<' not supported between instances of 'list' and 'int'

In [68]:
[x for x in mylist if x < 10 and x > -10]

[-1, 7, -5, 6, 3]

In [69]:
smalllist = []
for x in mylist:
    if x < 10 and x > -10:
        smalllist.append(x)

print(smalllist)

[-1, 7, -5, 6, 3]


In [70]:
[x for x in mylist if (x > -10) & (x < 10)]

[-1, 7, -5, 6, 3]

In [71]:
[x for x in mylist if not((x <= -10) or (x >= 10))]

[-1, 7, -5, 6, 3]

In [72]:
[x for x in mylist if not(x <= -10) and not(x >= 10)]

[-1, 7, -5, 6, 3]

In [73]:
arr

array([ -1,  46, -11, -34,   7,  -5,  38, -39,   6, -26, -47, -36,  21,
        19,  13, -37, -21,  35,   3,  12], dtype=int64)

In [74]:
arr < 10

array([ True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False, False, False,  True,  True, False,
        True, False])

In [75]:
bool = (arr > -10) & (arr < 10)   #success! It works similar to Matlab
print(bool)

[ True False False False  True  True False False  True False False False
 False False False False False False  True False]


In [76]:
arr[bool] #again like Matlab! Return the elements corresponding to True indices

array([-1,  7, -5,  6,  3], dtype=int64)

In [77]:
arr[(arr > -10) & (arr < 10)] 

array([-1,  7, -5,  6,  3], dtype=int64)

In [78]:
(arr <= -10) | (arr >=10)

array([False,  True,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [79]:
~(arr <= -10) | (arr >=10)

array([ True,  True, False, False,  True,  True,  True, False,  True,
       False, False, False,  True,  True,  True, False, False,  True,
        True,  True])

In [80]:
arr[~((arr <= -10) | (arr >= 10))]

array([-1,  7, -5,  6,  3], dtype=int64)

In [81]:
~(arr <=-10) & ~(arr >=10)

array([ True, False, False, False,  True,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False])

In [82]:
arr[~(arr <= -10) & ~(arr >= 10)]

array([-1,  7, -5,  6,  3], dtype=int64)

In [83]:
#Notice we get an error, need & symbol in numpy, the word and does not work.
(arr > -10) and (arr < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [84]:
import numpy as np

In [85]:
rng = np.random.default_rng()

In [86]:
four_rolls = rng.integers(1,7,size=4)
print(four_rolls)

[5 1 3 5]


In [87]:
np.max(four_rolls)

5

In [88]:
four_rolls.max()

5

In [89]:
exp = 10
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp    #number of successes / number of experiments is the experimental probability

0.2

In [90]:
%%time
exp = 10**6
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp

CPU times: total: 30.1 s
Wall time: 30.2 s


0.28413

In [91]:
exp = 10
rng.integers(1,7,size=(exp,4))

array([[5, 2, 5, 6],
       [1, 4, 1, 6],
       [4, 3, 1, 3],
       [5, 2, 3, 6],
       [4, 6, 6, 6],
       [2, 2, 3, 6],
       [2, 3, 2, 1],
       [3, 4, 1, 5],
       [4, 1, 6, 6],
       [3, 4, 6, 1]], dtype=int64)

In [92]:
arr = rng.integers(1,7,size=(exp,4))
print(arr)

[[3 6 4 2]
 [4 5 3 2]
 [2 3 5 3]
 [2 2 4 2]
 [6 6 2 3]
 [4 4 6 4]
 [6 6 2 1]
 [1 2 3 4]
 [2 3 3 5]
 [2 4 4 6]]


In [93]:
help(np.apply_along_axis)

Help on _ArrayFunctionDispatcher in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.

    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.

    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]

    Equivalently, eliminating the inner loop, this can be expressed as::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])

    

In [94]:
print(arr)

[[3 6 4 2]
 [4 5 3 2]
 [2 3 5 3]
 [2 2 4 2]
 [6 6 2 3]
 [4 4 6 4]
 [6 6 2 1]
 [1 2 3 4]
 [2 3 3 5]
 [2 4 4 6]]


In [95]:
np.max(arr)

6

In [96]:
np.apply_along_axis(np.max, axis=1, arr=arr)

array([6, 5, 5, 4, 6, 6, 6, 4, 5, 6], dtype=int64)

In [97]:
np.apply_along_axis(np.max, axis=1, arr=arr) == 5

array([False,  True,  True, False, False, False, False, False,  True,
       False])

In [98]:
np.apply_along_axis(np.max, axis=0, arr=arr)

array([6, 6, 6, 6], dtype=int64)

In [99]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()   #Recall: Numpy interprets True as 1 and False as 0 in numerical computations

0.1

In [100]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

CPU times: total: 11 s
Wall time: 11 s


0.28517

In [101]:
print(arr.max())
print(np.max(arr))

6
6


In [102]:
np.max(arr, axis=1)

array([4, 6, 5, ..., 5, 5, 6], dtype=int64)

In [103]:
arr.max(axis=1)

array([4, 6, 5, ..., 5, 5, 6], dtype=int64)

In [104]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

0.5

In [105]:
#1-Dimensional
(arr.max(axis=1) == 5)

array([False, False,  True,  True, False,  True, False,  True, False,
        True])

In [106]:
arr.max(axis=1).shape

(10,)

In [107]:
#axis = 0 is the default
(arr.max(axis=1) == 5).mean(axis=0)

0.5

In [108]:
(arr.max(axis=1) == 5).mean(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [109]:
help(arr.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

    Return the maximum along a given axis.

    Refer to `numpy.amax` for full documentation.

    See Also
    --------
    numpy.amax : equivalent function



In [110]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

CPU times: total: 46.9 ms
Wall time: 46.9 ms


0.285113