In [1]:
r = range(0,10**7,5)
mylist = list(r)
mytuple = tuple(r)
myset = set(r)

In [2]:
0 in mylist

True

In [3]:
1 in mylist

False

In [4]:
5 in mylist

True

In [5]:
%%timeit #Example of a Jupyter magic
0 in mytuple

23.5 ns ± 1.66 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [6]:
%%timeit
0 in mylist

25.9 ns ± 1.8 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [7]:
%%timeit
0 in myset

31 ns ± 2.03 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [8]:
%%timeit
1 in mytuple

17.9 ms ± 751 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%%timeit
1 in mylist

22.4 ms ± 4.29 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%timeit 
1 in myset

31.9 ns ± 2.23 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [11]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

In [12]:
print(f(4))

None


In [13]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [14]:
f(10)

[3]

In [15]:
f(5)

[3]

In [16]:
def f(n):
    mylist = []
    for _ in range(n):   #underscore is useful when you don't use the variable in the loop
        mylist.append(3)
    return mylist

f(8)

[3, 3, 3, 3, 3, 3, 3, 3]

In [17]:
f(3)

[3, 3, 3]

In [18]:
f(4)

[3, 3, 3, 3]

In [19]:
f(0)

[]

In [20]:
f(7)

[3, 3, 3, 3, 3, 3, 3]

In [21]:
n

NameError: name 'n' is not defined

In [22]:
n = 100
f(4)

[3, 3, 3, 3]

In [23]:
n

100

In [24]:
def constant(n):
    mylist = []
    for _ in range(n):
        mylist.append(3)
    return mylist

In [25]:
def alt1(n):
    mylist = constant(n)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

In [26]:
#mylist[1::2] = 7   #notation like this doesn't work for python lists. Need python arrays (later in this page)

In [27]:
alt1(4)

[3, 7, 3, 7]

In [28]:
alt1(5)

[3, 7, 3, 7, 3]

In [29]:
alt1(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [30]:
def alt2(n):
    mylist = []
    for i in range(n):
        if i%2 == 0:     #i mod 2 equals 0 is the same as saying i has no remainder when we divide by 2. This means i is even.
            mylist.append(3)
        else:
            mylist.append(7)
    return mylist

In [31]:
def cycle_three(n):  #gives lists of the form [3, 7, 6, 3, 7, 6, ... ]
    mylist = []
    for i in range(n): #i represents the index of mylist
        if i%3 == 0:  #if i divided by 3 has zero for a remainder. Same as if i were a multiple of 3.
            mylist.append(3)
        elif i%3 == 1:
            mylist.append(7)
        else:
            mylist.append(6)
    return mylist

In [32]:
5%2

1

In [33]:
7%2

1

In [34]:
4%2

0

In [35]:
alt2(20)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [36]:
alt2(6)

[3, 7, 3, 7, 3, 7]

In [37]:
cycle_three(4)

[3, 7, 6, 3]

In [38]:
cycle_three(20)

[3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7]

In [39]:
import numpy as np

In [40]:
np.zeros((3,4)) #notice the dimensions are in a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
np.zeros((3,4)).shape

(3, 4)

In [43]:
A = np.zeros((3,5))
type(A)

numpy.ndarray

In [44]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros(7).shape

(7,)

In [46]:
np.zeros(7).ndim

1

In [47]:
np.zeros((1,7))

array([[0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros((1,7)).shape

(1, 7)

In [49]:
np.zeros((1,7)).ndim

2

In [50]:
type(np.zeros(7)[0])

numpy.float64

In [51]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [52]:
np.zeros(7,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [53]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64)
    return A

In [54]:
alt3(4)

array([0, 0, 0, 0], dtype=int64)

In [55]:
alt3(4).shape

(4,)

In [56]:
alt3(5) + 3    #This trick is known as broadcasting, and it works in Matlab. Does not work for lists in Python, but works for ndarrays

array([3, 3, 3, 3, 3], dtype=int64)

In [57]:
#constant with all threes
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    return A

In [58]:
mylist = [0,0,0]

In [59]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [60]:
mylist + [3]

[0, 0, 0, 3]

In [61]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7   #This also works in Matlab! We broadcasted assignment across a slice of an array. Python lists cannot do this, but ndarrays can
    return A

In [62]:
alt3(10)

array([3, 7, 3, 7, 3, 7, 3, 7, 3, 7], dtype=int64)

In [63]:
alt3(4)

array([3, 7, 3, 7], dtype=int64)

In [64]:
mylist = [3,1,4,1,5,9]

In [65]:
mylist[::2]  #can call a slice of a list

[3, 4, 5]

In [66]:
mylist[::2] = -17

TypeError: must assign iterable to extended slice

In [67]:
mylist[::2] = [-17,-17,-17]
mylist

[-17, 1, -17, 1, -17, 9]

In [68]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return A

In [69]:
def alt3_mimic(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

In [70]:
alt3_mimic(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [71]:
alt3_mimic(5)

[3, 7, 3, 7, 3]

In [72]:
%%timeit 
alt3_mimic(10)

725 ns ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [73]:
#comes with python, no installation
import time 

In [74]:
time.time()

1741164225.9942186

In [75]:
time.time()

1741164226.0004067

In [76]:
start = time.time()
alt3_mimic(10**5)
end = time.time()
t = end - start

In [77]:
t

0.008254528045654297

In [78]:
t = 0
n = 100
while t < 5:
    n = 2*n
    start = time.time()
    alt3_mimic(n)
    end = time.time()
    t = end-start

In [79]:
t

9.573212385177612

In [80]:
n

104857600

In [81]:
print(n)
start = time.time()
alt3(n)
end = time.time()
t = end-start
print(t)

104857600


0.5769360065460205


In [82]:
def alt3_list(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return list(A)   #Convert numpy array to a list

In [83]:
print(n)
start = time.time()
alt3_list(n)
end = time.time()
t = end-start
print(t)

104857600


10.108603239059448


In [84]:
def alt3_loop(n):
    A = np.zeros(n,dtype=np.int64) + 3
    for i in range(1,n,2):
        A[i] = 7
    return A

In [85]:
print(n)
start = time.time()
alt3_loop(n)
end = time.time()
t = end-start
print(t)

104857600


4.996786832809448


In [86]:
import numpy as np
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [87]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

In [88]:
np.zeros((3,5)) + 7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [89]:
np.ones((3,5), dtype=np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [90]:
np.ones((3,5), dtype=np.int64)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int64)

In [91]:
import numpy as np

In [92]:
arr=np.zeros((2,5), dtype=int)
arrshape = arr.shape
print(arrshape[0])
print(arrshape[1])
for row in range(arrshape[0]):
    for col in range(arrshape[1]):
        arr[row,col] = 2 + 3*col + 15*row
arr

2
5


array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [93]:
print([0, 1, 2, 3])  #list
np.array([0, 1, 2, 3]) #numpy array

[0, 1, 2, 3]


array([0, 1, 2, 3])

In [94]:
print(range(4))
np.arange(4)  #Still computationally efficient, even though all elements are listed

range(0, 4)


array([0, 1, 2, 3])

In [95]:
arr2=np.arange(2,30,3)
print(arr2)

[ 2  5  8 11 14 17 20 23 26 29]


In [96]:
arr2.reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [97]:
np.arange(2,30,3).reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [98]:
np.arange(2,30,3).reshape((3,2))

ValueError: cannot reshape array of size 10 into shape (3,2)

In [99]:
np.arange(2,30,3).reshape((-1,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [100]:
np.arange(2,30,3).reshape((2,-1))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [101]:
np.arange(2,30,3).reshape((-1,2))

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])