In [1]:
import numpy as np

In [2]:
np.random.randint(-22, 39,size=(2,5))

array([[-15,  38, -10,  14,  -4],
       [ 31,  12,  -9,  32,   3]])

In [3]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [4]:
rng = np.random.default_rng()

In [5]:
type(rng)

numpy.random._generator.Generator

In [6]:
arr = rng.integers(0,39,size=10)

In [7]:
arr

array([14, 36, 27, 16, 27, 17, 29, 19, 24, 10], dtype=int64)

In [8]:
rng.choice(arr,size=5)

array([27, 27, 17, 36, 27], dtype=int64)

In [9]:
help(rng.choice)

Help on built-in function choice:

choice(...) method of numpy.random._generator.Generator instance
    choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)

    Generates a random sample from a given array

    Parameters
    ----------
    a : {array_like, int}
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated from np.arange(a).
    size : {int, tuple[int]}, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn from the 1-d `a`. If `a` has more
        than one dimension, the `size` shape will be inserted into the
        `axis` dimension, so the output ``ndim`` will be ``a.ndim - 1 +
        len(size)``. Default is None, in which case a single value is
        returned.
    replace : bool, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``a`` can be selected multiple 

In [10]:
arr2 = np.arange(0,100,3)
print(arr2)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [11]:
rng.choice(arr2,size=5)

array([84,  3, 39, 18, 27])

In [12]:
rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [13]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)

    Return random floats in the half-open interval [0.0, 1.0).

    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` use `uniform`
    or multiply the output of `random` by ``(b - a)`` and add ``a``::

        (b - a) * random() + a

    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
 

In [14]:
#3x5 array of random reals between 0 and 1
rng.random((3,5))

array([[0.10760851, 0.66698668, 0.89561723, 0.98345765, 0.00215335],
       [0.76054404, 0.29634411, 0.8381186 , 0.90233688, 0.24119357],
       [0.44410113, 0.64982237, 0.42627122, 0.45300098, 0.17430479]])

In [15]:
#Mult. by 5 to stretch to correct length
5*rng.random((3,5))

array([[1.32621315, 2.35445347, 0.43522202, 2.74360403, 2.59085518],
       [2.35656474, 3.18179083, 2.19450321, 1.50287353, 1.38939946],
       [4.30369384, 3.91931404, 1.05827727, 3.73154515, 1.35926156]])

In [16]:
#subtract 1 to shift to correct interval.
5*rng.random((3,5))-1

array([[ 3.21492658,  0.62849897,  1.73582586,  2.7344547 ,  3.92223569],
       [ 1.43583279, -0.01854868,  3.19185269,  0.46436826, -0.23018454],
       [-0.31492223,  2.52493459, -0.06436466,  1.99976259,  2.13966281]])

In [17]:
help(rng.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or tuple of ints,

In [18]:
rng.normal(2,0.1,size=10)

array([2.00324014, 2.14065526, 2.01353009, 1.89117726, 1.89896744,
       2.04628929, 2.15095983, 1.96712314, 1.93408039, 2.03309001])

In [19]:
import numpy as np

In [20]:
ThisMat = np.zeros((4,4), dtype=int)
print(ThisMat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
for row in range(4):
    for col in range(4):
        ThisMat[row, col] = row
print(ThisMat)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [22]:
ThisMat[3] +3

array([6, 6, 6, 6])

In [23]:
ThisMat[:,3] + 3   #even though I referenced a column, the output is given as a row, it only has 1-dim.

array([3, 4, 5, 6])

In [24]:
ThisMat[:,3] = ThisMat[:,3] + 3
print(ThisMat)

[[0 0 0 3]
 [1 1 1 4]
 [2 2 2 5]
 [3 3 3 6]]


In [25]:
ThisMat[:,3] += 3   #This shortcut works in Python, and it didn't work in Matlab!
print(ThisMat)

[[0 0 0 6]
 [1 1 1 7]
 [2 2 2 8]
 [3 3 3 9]]


In [26]:
ThisMat = np.zeros((4,4), dtype=int)
for n in range(4):
    ThisMat[n] += n   #shortcut for ThisMat[n] = ThisMat[n] + n
print(ThisMat)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [27]:
ThisMat[1]

array([1, 1, 1, 1])

In [28]:
ThisMat[1,0]

1

In [29]:
print([0, 1, 2, 3])
np.array([0,1,2,3])

[0, 1, 2, 3]


array([0, 1, 2, 3])

In [30]:
print(range(4))
np.arange(4)  #Still computationally efficient, even though all elements are listed

range(0, 4)


array([0, 1, 2, 3])

In [31]:
ThatMat = np.zeros((4,4), dtype=int)
print(ThatMat)
ThatMat = ThatMat + np.arange(4)
ThatMat

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [32]:
ThatMat.T    #Transpose of ThatMat. Rows swap to Columns, and vice versa.

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [33]:
OurMat = np.zeros((4,4), dtype=int)
OurMat[1] = np.arange(4)
print(OurMat)

[[0 0 0 0]
 [0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [34]:
OurMat = np.zeros((4,4), dtype=int)
OurMat[:] = np.arange(4)  #replace all rows with np.arange(4). The shape broadcasts across the entire array
print(OurMat)
print() #blank line, for spacing the outputs
print(OurMat.T)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [35]:
np.arange(4).T #Does not change with a transpose. This is because there is only one dimension to its shape

array([0, 1, 2, 3])

In [36]:
print(np.arange(4).shape)
print(np.arange(4).ndim)

(4,)
1


In [37]:
np.array([[0], [1], [2] ,[3]]) #A little annoying to write, even though it's only 4 entries

array([[0],
       [1],
       [2],
       [3]])

In [38]:
np.array([[0, 1, 2, 3]]).T  #Slightly less annoying, but still hard for longer arrays. Double [[ ]] required for 2-dimensional array and transpose.

array([[0],
       [1],
       [2],
       [3]])

In [39]:
np.arange(4).reshape(4,1)  #Best method overall!

array([[0],
       [1],
       [2],
       [3]])

In [40]:
arr = np.zeros((4,4), dtype=int)
print(arr)
print()
z = np.arange(4).reshape(4,1)
print(z)
arr = arr + z
print()
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]



[[0]
 [1]
 [2]
 [3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [41]:
arr[3]

array([3, 3, 3, 3])

In [42]:
arr[3] = [2,10]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [43]:
arr[3] = [2,10,2,10]
arr

array([[ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [44]:
arr[0] = 5
arr

array([[ 5,  5,  5,  5],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [45]:
arr[:,0:2] = 99
arr

array([[99, 99,  5,  5],
       [99, 99,  1,  1],
       [99, 99,  2,  2],
       [99, 99,  2, 10]])

In [46]:
[1,3,4,7].reshape(4,1)   #lists cannot be reshaped. We need numpy arrays in order to reshape

AttributeError: 'list' object has no attribute 'reshape'

In [47]:
arr.shape

(4, 4)

In [48]:
w = np.array([1,3,4,7])

In [49]:
w.shape

(4,)

In [50]:
w.reshape(2,2)

array([[1, 3],
       [4, 7]])

In [51]:
import numpy as np

In [52]:
v1 = np.arange(7).reshape(1,7)
print(v1)
print()
A1 = np.zeros((8,7), dtype = int) + v1
print(A1)

[[0 1 2 3 4 5 6]]

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


In [53]:
v2 = np.arange(8).reshape(8,1)
print(v2)
print()
A2 = np.zeros((8,7), dtype = int) + v2
print(A2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

[[0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7]]


In [54]:
v1+v2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [55]:
A1 + A2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [56]:
v1+v2 == A1 + A2

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [57]:
NewArr = np.arange(1,25).reshape(4,6)
NewArr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [58]:
NewArr + [[1, 1, 11, 1, 1, 1]]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [59]:
np.array([[1, 1, 11, 1, 1, 1]]).shape

(1, 6)

In [60]:
NewArr + [1, 1, 11, 1, 1, 1]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [61]:
np.array([1, 1, 11, 1, 1, 1]).shape

(6,)

In [62]:
NewArr + [5 , 9, 0, 9]

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [63]:
NewArr + [[5 , 9, 0, 9]]

ValueError: operands could not be broadcast together with shapes (4,6) (1,4) 

In [64]:
vecbroadcast1 = np.array([5, 9, 0, 9]).reshape(-1,1)   #the -1 is replaced with whichever number makes this shape work, depending on number of elts.
print(vecbroadcast1)

[[5]
 [9]
 [0]
 [9]]


In [65]:
print(NewArr)
NewArr + vecbroadcast1

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

In [66]:
NewArr +  [[5], [9], [0], [9]]

array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

In [67]:
a = np.arange(5).reshape(5,1)
b = np.arange(6).reshape(1,6)
c = np.arange(10,16)

print(a)
print(a.shape)
print()
print(b)
print(b.shape)
print()
print(c)
print(c.shape)
d = 15

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)

[[0 1 2 3 4 5]]
(1, 6)

[10 11 12 13 14 15]
(6,)


In [68]:
TheArr = np.arange(30).reshape(5,6)
print(TheArr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [69]:
print(TheArr + a)
print(TheArr*a)

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]
 [28 29 30 31 32 33]]
[[  0   0   0   0   0   0]
 [  6   7   8   9  10  11]
 [ 24  26  28  30  32  34]
 [ 54  57  60  63  66  69]
 [ 96 100 104 108 112 116]]


In [70]:
print(TheArr + b)
print(TheArr*b)

[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]]
[[  0   1   4   9  16  25]
 [  0   7  16  27  40  55]
 [  0  13  28  45  64  85]
 [  0  19  40  63  88 115]
 [  0  25  52  81 112 145]]


In [71]:
TheArr[0::2] = c #replace every other row with c
print(TheArr)

[[10 11 12 13 14 15]
 [ 6  7  8  9 10 11]
 [10 11 12 13 14 15]
 [18 19 20 21 22 23]
 [10 11 12 13 14 15]]


In [72]:
TheArr[1:5:2] = TheArr[1:5:2] + b
print(TheArr)

[[10 11 12 13 14 15]
 [ 6  8 10 12 14 16]
 [10 11 12 13 14 15]
 [18 20 22 24 26 28]
 [10 11 12 13 14 15]]


In [73]:
print(TheArr) #before

print()

TheArr[1:5:2] += b #  += is a shortcut for TheArr[1:5:2] = TheArr[1:5:2] + b. We can also use *= and -= as shortcuts.
print(TheArr) #after

[[10 11 12 13 14 15]
 [ 6  8 10 12 14 16]
 [10 11 12 13 14 15]
 [18 20 22 24 26 28]
 [10 11 12 13 14 15]]

[[10 11 12 13 14 15]
 [ 6  9 12 15 18 21]
 [10 11 12 13 14 15]
 [18 21 24 27 30 33]
 [10 11 12 13 14 15]]


In [74]:
import numpy as np

In [75]:
rng = np.random.default_rng()
n = 20
arr = rng.integers(-50,51, size=n)
mylist = list(arr)

In [76]:
mylist

[17,
 -34,
 15,
 -45,
 -36,
 -21,
 -14,
 17,
 4,
 9,
 50,
 32,
 -4,
 12,
 -15,
 -1,
 -13,
 0,
 -14,
 26]

In [77]:
mylist < 10    #cannot compare an entire list to an integer. But does this work for an array?

TypeError: '<' not supported between instances of 'list' and 'int'

In [78]:
[x for x in mylist  if x < 10 and x > -10]

[4, 9, -4, -1, 0]

In [79]:
smalllist = []
for x in mylist:
    if x < 10 and x > -10:
        smalllist.append(x)

print(smalllist)

[4, 9, -4, -1, 0]


In [80]:
[x for x in mylist if (x > -10) & (x < 10)]

[4, 9, -4, -1, 0]

In [81]:
[x for x in mylist if not((x <= -10) or (x >= 10))]

[4, 9, -4, -1, 0]

In [82]:
[x for x in mylist if not(x <= -10) and not(x >= 10)]

[4, 9, -4, -1, 0]

In [83]:
arr

array([ 17, -34,  15, -45, -36, -21, -14,  17,   4,   9,  50,  32,  -4,
        12, -15,  -1, -13,   0, -14,  26], dtype=int64)

In [84]:
arr < 10

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
        True, False])

In [85]:
bool = (arr > -10) & (arr < 10)   #success! It works similar to Matlab
print(bool)

[False False False False False False False False  True  True False False
  True False False  True False  True False False]


In [86]:
arr[bool] #again like Matlab! Return the elements corresponding to True indices

array([ 4,  9, -4, -1,  0], dtype=int64)

In [87]:
arr[(arr > -10) & (arr < 10)] 

array([ 4,  9, -4, -1,  0], dtype=int64)

In [88]:
(arr <= -10) | (arr >=10)

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True, False,  True, False,
        True,  True])

In [89]:
~(arr <= -10) | (arr >=10)

array([ True, False,  True, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [90]:
arr[~((arr <= -10) | (arr >= 10))]

array([ 4,  9, -4, -1,  0], dtype=int64)

In [91]:
~(arr <=-10) & ~(arr >=10)

array([False, False, False, False, False, False, False, False,  True,
        True, False, False,  True, False, False,  True, False,  True,
       False, False])

In [92]:
arr[~(arr <= -10) & ~(arr >= 10)]

array([ 4,  9, -4, -1,  0], dtype=int64)

In [93]:
#Notice we get an error, need & symbol in numpy, the word and does not work.
(arr > -10) and (arr < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [94]:
arr != 3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [95]:
import numpy as np

In [96]:
rng = np.random.default_rng()

In [97]:
four_rolls = rng.integers(1,7,size=4)
print(four_rolls)

[4 2 1 5]


In [98]:
np.max(four_rolls)

5

In [99]:
four_rolls.max()

5

In [100]:
exp = 10  #number of experiments
s = 0  #number of successes
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:  #if the max of 4 rolls equals 5, all in one line. Can expand this to more lines if it's easier for you.
        s += 1 #shorthand for s = s+1
s/exp    #number of successes / number of experiments is the experimental probability

0.3

In [101]:
%%time
exp = 10**6
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp

CPU times: total: 47 s
Wall time: 50 s


0.28501

In [102]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
print(arr)

[[6 4 4 5]
 [3 4 5 2]
 [5 4 5 1]
 [6 4 1 5]
 [3 1 2 1]
 [5 6 6 3]
 [5 5 4 4]
 [2 3 2 3]
 [2 2 4 3]
 [1 2 5 4]]


In [103]:
help(np.apply_along_axis)

Help on _ArrayFunctionDispatcher in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.

    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.

    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]

    Equivalently, eliminating the inner loop, this can be expressed as::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])

    

In [104]:
print(arr)

[[6 4 4 5]
 [3 4 5 2]
 [5 4 5 1]
 [6 4 1 5]
 [3 1 2 1]
 [5 6 6 3]
 [5 5 4 4]
 [2 3 2 3]
 [2 2 4 3]
 [1 2 5 4]]


In [105]:
np.max(arr)  #Maximum out of all 40 entries

6

In [106]:
np.apply_along_axis(np.max, axis=1, arr=arr)

array([6, 5, 5, 6, 3, 6, 5, 3, 4, 5], dtype=int64)

In [107]:
np.apply_along_axis(np.max, axis=1, arr=arr) == 5

array([False,  True,  True, False, False, False,  True, False, False,
        True])

In [108]:
np.apply_along_axis(np.max, axis=0, arr=arr)

array([6, 6, 6, 5], dtype=int64)

In [109]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()   #Recall: Numpy interprets True as 1 and False as 0 in numerical computations

0.0

In [110]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
print(arr)
print()
rowmax = np.apply_along_axis(np.max,axis=1,arr=arr)
print(rowmax)
print()
indicator = rowmax == 5
print(indicator)
print()
print(indicator.sum())
print(indicator.sum()/exp) #this step can be replicated by taking the mean
print(indicator.mean())
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()   #Recall: Numpy interprets True as 1 and False as 0 in numerical computations

[[1 6 4 6]
 [6 6 4 1]
 [2 4 3 2]
 [2 2 2 1]
 [3 4 5 2]
 [3 1 6 3]
 [6 6 4 2]
 [2 6 1 2]
 [2 3 6 4]
 [4 6 5 2]]

[6 6 4 2 5 6 6 6 6 6]

[False False False False  True False False False False False]

1
0.1
0.1


0.1

In [111]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

CPU times: total: 16.4 s
Wall time: 17 s


0.285185

In [112]:
print(arr.max())
print(np.max(arr))

6
6


In [113]:
np.max(arr, axis=1)

array([5, 6, 4, ..., 6, 5, 6], dtype=int64)

In [114]:
arr.max(axis=1)

array([5, 6, 4, ..., 6, 5, 6], dtype=int64)

In [115]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

0.3

In [116]:
#1-Dimensional
(arr.max(axis=1) == 5)

array([False, False,  True,  True, False, False, False, False, False,
        True])

In [117]:
arr.max(axis=1).shape

(10,)

In [118]:
#axis = 0 is the default
(arr.max(axis=1) == 5).mean(axis=0)

0.3

In [119]:
(arr.max(axis=1) == 5).mean(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [120]:
help(arr.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

    Return the maximum along a given axis.

    Refer to `numpy.amax` for full documentation.

    See Also
    --------
    numpy.amax : equivalent function



In [121]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

CPU times: total: 125 ms
Wall time: 136 ms


0.284474

In [122]:
9/36   #Theoretical result for roll 2 die, max equals 5. It matches if you change size(exp,4) to size(exp,2)
#Can talk more about this in office hours.

0.25