In [1]:
r = range(0,10**7,5)
mylist = list(r)
mytuple = tuple(r)
myset = set(r)

In [2]:
0 in mylist

True

In [3]:
1 in mylist

False

In [4]:
5 in mylist

True

In [5]:
%%timeit #Example of a Jupyter magic
0 in mytuple

65.4 ns ± 7.63 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [6]:
%%timeit
0 in mylist

62 ns ± 5.08 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [7]:
%%timeit
0 in myset

62.4 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [8]:
%%timeit
1 in mytuple

27 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
1 in mylist

33.6 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit 
1 in myset

59.4 ns ± 5.51 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [11]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

In [12]:
f(3)

In [13]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [14]:
f(3)

[3]

In [15]:
f(5)

[3]

In [16]:
def f(n):
    mylist = []
    for _ in range(n):   #underscore is useful when you don't use the variable in the loop
        mylist.append(3)
    return mylist

f(8)

[3, 3, 3, 3, 3, 3, 3, 3]

In [17]:
f(3)

[3, 3, 3]

In [18]:
f(4)

[3, 3, 3, 3]

In [19]:
f(0)

[]

In [20]:
f(7)

[3, 3, 3, 3, 3, 3, 3]

In [21]:
n

NameError: name 'n' is not defined

In [22]:
n = 100
f(4)

[3, 3, 3, 3]

In [23]:
n

100

In [24]:
def constant(n):
    mylist = []
    for _ in range(n):
        mylist.append(3)
    return mylist

In [25]:
def alt1(n):
    mylist = constant(n)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

In [26]:
#mylist[1::2] = 7   #notation like this doesn't work for python lists. Need python arrays (later in this page)

In [27]:
alt1(4)

[3, 7, 3, 7]

In [28]:
alt1(5)

[3, 7, 3, 7, 3]

In [29]:
alt1(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [30]:
def alt2(n):
    mylist = []
    for i in range(n): #i represents the index of mylist
        if i%2 == 0:  #if i divided by 2 has zero for a remainder. Same as if i were even.
            mylist.append(3)
        else:
            mylist.append(7)
    return mylist

In [31]:
def alt2a(n):
    mylist = []
    for i in range(n): #i represents the index of mylist
        if i%3 == 0:  #if i divided by 2 has zero for a remainder. Same as if i were even.
            mylist.append(3)
        elif i%3 == 1:
            mylist.append(7)
        else:
            mylist.append(6)
    return mylist

In [32]:
5%2

1

In [33]:
7%2

1

In [34]:
4%2

0

In [35]:
alt2(8)

[3, 7, 3, 7, 3, 7, 3, 7]

In [36]:
alt2(6)

[3, 7, 3, 7, 3, 7]

In [37]:
alt2a(4)

[3, 7, 6, 3]

In [38]:
alt2a(20)

[3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7, 6, 3, 7]

In [39]:
import numpy as np

In [40]:
np.zeros((3,4)) #notice the dimensions are in a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((3,4)).shape

(3, 4)

In [42]:
A = np.zeros((3,5))
type(A)

numpy.ndarray

In [43]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(7).shape

(7,)

In [45]:
np.zeros(7).ndim

1

In [46]:
type(np.zeros(7)[0])

numpy.float64

In [47]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [48]:
np.zeros(7,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [49]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64)
    return A

In [50]:
alt3(4)

array([0, 0, 0, 0], dtype=int64)

In [51]:
alt3(4).shape

(4,)

In [52]:
alt3(5) + 3    #This trick works in Matlab. Does not work for lists in Python, but works for ndarrays

array([3, 3, 3, 3, 3], dtype=int64)

In [53]:
#constant with all threes
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    return A

In [54]:
mylist = [0,0,0]

In [55]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

In [56]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7   #This also works in Matlab! Python lists cannot do this, but ndarrays can
    return A

In [57]:
alt3(10)

array([3, 7, 3, 7, 3, 7, 3, 7, 3, 7], dtype=int64)

In [58]:
alt3(4)

array([3, 7, 3, 7], dtype=int64)

In [59]:
mylist = [3,1,4,1,5,9]

In [60]:
mylist[::2]

[3, 4, 5]

In [61]:
mylist[::2] = -17

TypeError: must assign iterable to extended slice

In [62]:
mylist[::2] = [-17,-17,-17]
mylist

[-17, 1, -17, 1, -17, 9]

In [63]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return A

In [64]:
def alt4(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

In [65]:
alt4(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [66]:
alt4(5)

[3, 7, 3, 7, 3]

In [67]:
%%timeit 
alt4(10)

1.46 μs ± 132 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [68]:
#comes with python, no installation
import time 

In [69]:
time.time()

1740720626.6325877

In [70]:
time.time()

1740720626.642698

In [71]:
start = time.time()
alt4(10**5)
end = time.time()
t = end - start

In [72]:
t

0.009027481079101562

In [73]:
t = 0
n = 100
while t < 5:
    n = 2*n
    start = time.time()
    alt4(n)
    end = time.time()
    t = end-start

In [74]:
t

6.177607774734497

In [75]:
n

52428800

In [76]:
print(n)
start = time.time()
alt3(n)
end = time.time()
t = end-start
print(t)

52428800


0.2941622734069824


In [77]:
def alt3a(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return list(A)

In [78]:
print(n)
start = time.time()
alt3a(n)
end = time.time()
t = end-start
print(t)

52428800


3.887525796890259


In [79]:
def alt3b(n):
    A = np.zeros(n,dtype=np.int64) + 3
    for i in range(1,n,2):
        A[i] = 7
    return A

In [80]:
print(n)
start = time.time()
alt3b(n)
end = time.time()
t = end-start
print(t)

52428800


4.889943838119507


In [81]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is exc

In [82]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

In [83]:
np.zeros((3,5)) + 7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [84]:
np.ones((3,5), dtype=np.int64)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int64)

In [85]:
ThisMat = np.zeros((5,5), dtype=int)
print(ThisMat)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [86]:
ThisMat[3] +3

array([3, 3, 3, 3, 3])

In [87]:
for n in range(5):
    ThisMat[n] = ThisMat[n] + n
print(ThisMat)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [88]:
ThisMat[1]

array([1, 1, 1, 1, 1])

In [89]:
ThisMat[1,0]

1

In [90]:
range(5)

range(0, 5)

In [91]:
np.arange(5)  #Still computationally efficient, even though all elements are listed

array([0, 1, 2, 3, 4])

In [92]:
ThisMat[:,4] = np.arange(5)
print(ThisMat)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [93]:
ThisMat[:]

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [94]:
ThatMat = np.zeros((5,5), dtype=int)
#ThatMat[1] = [1, 2, 3, 4, 5]
ThatMat[:] = [0, 1, 2, 3, 4]  #replace every row with [1,2,3,4,5]

In [95]:
ThatMat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [96]:
ThatMat.T  #Transpose

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [97]:
1/ThatMat  #pointwise division, not a true matrix inverse

C:\Users\Luke\AppData\Local\Temp\ipykernel_13864\4161609170.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ThatMat  #pointwise division, not a true matrix inverse


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [       inf, 1.        , 0.5       , 0.33333333, 0.25      ]])

In [98]:
OurMat = np.zeros((5,5), dtype=int)
OurMat = OurMat + np.array([[1,2,3,4,5]]).T  #alternate: add a column to every column
OurMat

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [99]:
[1,2,3,4,5].T   #cannot transpose a list

AttributeError: 'list' object has no attribute 'T'

In [100]:
np.array([1, 2, 3, 4, 5]).T   #can transpose a 1-dim array, but the shape doesn't change

array([1, 2, 3, 4, 5])

In [101]:
np.array([1, 2, 3, 4, 5]).shape  #Only 1-dim in shape

(5,)

In [102]:
np.array([[1, 2, 3, 4, 5]]).shape   #Double up on [[ ]] to get 2-dimensional shape

(1, 5)

In [103]:
np.array([[1, 2, 3, 4, 5]]).T #Now transpose works as expected

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
import numpy as np

In [105]:
arr=np.zeros((2,5), dtype=int)
arrshape = arr.shape
for i in range(arrshape[0]):
    for j in range(arrshape[1]):
        arr[i,j] = 2 + 3*j + 3*arrshape[1]*i #np arrays can be double-indexed. Fill in the rest of this line, fitting the pattern above.
print(arr)

[[ 2  5  8 11 14]
 [17 20 23 26 29]]


In [106]:
arr2=np.arange(2,30,3)
print(arr2)

[ 2  5  8 11 14 17 20 23 26 29]


In [107]:
arr2.reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [108]:
np.arange(2,30,3).reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])