In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

In [3]:
arr = rng.integers(1, 10, size = 10**6)

In [4]:
arr[:5]

array([2, 6, 8, 2, 8], dtype=int64)

In [5]:
1.5/arr[:5]

array([0.75  , 0.25  , 0.1875, 0.75  , 0.1875])

In [6]:
mylist = list(arr)

In [7]:
mylist[:5]

[2, 6, 8, 2, 8]

In [8]:
#method 1 -- use a for loop
newlist = []
for x in mylist[:5]:
    newlist.append(1.5/x)
newlist

[0.75, 0.25, 0.1875, 0.75, 0.1875]

In [9]:
#method 2 -- list comprehension
[1.5/x for x in mylist[:5]]

[0.75, 0.25, 0.1875, 0.75, 0.1875]

In [10]:
%%timeit
1.5/arr[:5]

2.95 μs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%%timeit
newlist = []
for x in mylist[:5]:
    newlist.append(1.5/x)

14.4 μs ± 327 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
%%timeit
[1.5/x for x in mylist[:5]]

14 μs ± 305 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
#importy numpy as np
#rng = np.random.default_rng()

In [14]:
n = 10**7

In [15]:
arr = rng.integers(-50, 51, size=n)

In [16]:
mylist = list(arr)

In [17]:
count = 0
for x in mylist:
    if x < 10:
        count += 1
count

5940615

In [18]:
len([x for x in mylist if x < 10])

5940615

In [19]:
arr < 10

array([False,  True, False, ..., False, False, False])

In [20]:
np.count_nonzero(arr < 10)

5940615

In [21]:
np.nonzero(arr < 10)

(array([      1,      11,      12, ..., 9999990, 9999994, 9999995],
       dtype=int64),)

In [22]:
newlist = []
for x in mylist:
    if x < 10:
        newlist.append(x)

In [23]:
#[x for x in mylist if x < 10]

In [24]:
arr[arr < 10]

array([-42, -20, -26, ..., -14, -30, -28], dtype=int64)

In [25]:
%%timeit
count = 0
for x in mylist:
    if x < 10:
        count += 1
count/n

1 s ± 113 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
%%timeit
len([x for x in mylist if x < 10])/n

877 ms ± 48.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%%timeit
np.count_nonzero(arr < 10)/n

11.5 ms ± 316 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
