# Lectures 22-24

## Random Numbers

__Note:__ I’m first going to show you the old way of generating random numbers in NumPy. If you’re reading older code, this is likely the way you’ll see random numbers generated. All new code should be written using the new method that I show you.

__Older Method:__ Don't use this!

In [2]:
import numpy as np

In [10]:
np.random.randint(-22, 39,size=(2,5))

array([[  9, -21,  21,   2, -22],
       [ -5,  20, -22, -17, -18]])

In [6]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

__New Method:__ This is an example of object oriented programming (OOP)

In [12]:
rng = np.random.default_rng()

In [14]:
type(rng)

numpy.random._generator.Generator

* Make a length 10 NumPy array of random integers between 0 (inclusive) and 39 (exclusive).

In [16]:
arr = rng.integers(0,39,size=10)

In [18]:
arr

array([33, 36, 20, 18, 16, 11, 26, 32,  1, 25], dtype=int64)

* Choose five of those numbers (with replacement) and put them into a NumPy array.

In [20]:
rng.choice(arr,size=5)

array([11, 32, 32, 11, 36], dtype=int64)

In [22]:
help(rng.choice)

Help on built-in function choice:

choice(...) method of numpy.random._generator.Generator instance
    choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)

    Generates a random sample from a given array

    Parameters
    ----------
    a : {array_like, int}
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated from np.arange(a).
    size : {int, tuple[int]}, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn from the 1-d `a`. If `a` has more
        than one dimension, the `size` shape will be inserted into the
        `axis` dimension, so the output ``ndim`` will be ``a.ndim - 1 +
        len(size)``. Default is None, in which case a single value is
        returned.
    replace : bool, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``a`` can be selected multiple 

In [30]:
arr2 = np.arange(0,100,3)
print(arr2)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [34]:
rng.choice(arr2,size=5)

array([ 9, 63, 93, 78, 42])

### Create a $3 \times 5$ NumPy array of random real numbers between -1 and 4.

You might expect this to work, but it won't :(

In [36]:
rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [38]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)

    Return random floats in the half-open interval [0.0, 1.0).

    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` use `uniform`
    or multiply the output of `random` by ``(b - a)`` and add ``a``::

        (b - a) * random() + a

    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
 

In [40]:
#3x5 array of random reals between 0 and 1
rng.random((3,5))

array([[0.97304273, 0.33965199, 0.39927441, 0.34598293, 0.97235687],
       [0.62267724, 0.91852683, 0.30558521, 0.13108386, 0.28252921],
       [0.22049877, 0.84278028, 0.11553403, 0.51820206, 0.64594792]])

In [41]:
#Mult. by 5 to stretch to correct length
5*rng.random((3,5))

array([[0.13557807, 0.18956688, 2.12153   , 1.42358556, 0.09396672],
       [1.05150686, 2.28805592, 4.70145292, 1.21884137, 2.00933768],
       [0.75679007, 4.60186051, 3.12589336, 4.5860816 , 1.67790807]])

In [46]:
#subtract 1 to shift to correct interval.
5*rng.random((3,5))-1

array([[-0.92232721,  1.31149694,  1.30167455,  3.37295539,  1.1462322 ],
       [-0.39008005,  1.60329192,  1.1376222 , -0.25041937,  0.94270098],
       [ 0.74073331,  2.47189206,  3.04726996, -0.82625937,  1.34643629]])

Running the above cell a few times, we see that we can get pretty close to both -1 and 4.

* Create a length 10 NumPy array of random numbers that follow a normal distribution with mean 2 and standard deviation 0.1.

This isn't super important for our class, I just wanted to show it as an example.

In [57]:
help(rng.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int or tuple of ints,

In [64]:
rng.normal(2,0.1,size=10)

array([1.91357675, 2.16012324, 2.06283954, 2.05141019, 1.91897531,
       1.981415  , 2.22769399, 1.98032609, 1.99000895, 1.83026681])

Notice: the values are clustered around 2, and if they deviate from the average, it's likely within 0.1.

More specifically (according to stats or probability), 68% of values lie within one standard deviation, i.e. $ \pm 0.1$, of the mean 2. 

95% of values lie within 2 standard deviations, i.e. $ \pm 0.2$, of the mean 2.

### Broadcasting in Numpy

![](../images/12.jpg)
![](../images/13.jpg)
![](../images/14.jpg)
![](../images/15.jpg)
![](../images/16.jpg)
![](../images/17.jpg)
![](../images/18.jpg)
![](../images/19.jpg)
![](../images/20.jpg)
![](../images/21.jpg)
![](../images/22.jpg)

## Changing Rows and Columns, and examples of broadcasting

__Goal:__ Modify rows and columns of NumPy arrays.

* Construct The $4 \times 4$ matrix 

$
\begin{pmatrix}
0 & 0 & 0 & 0  \\
1 & 1 & 1 & 1  \\
2 & 2 & 2 & 2  \\
3 & 3 & 3 & 3  \\
\end{pmatrix}
$

In [32]:
import numpy as np

In [4]:
ThisMat = np.zeros((4,4), dtype=int)
print(ThisMat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [6]:
for row in range(4):
    for col in range(4):
        ThisMat[row, col] = row
print(ThisMat)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [8]:
ThisMat[3] +3

array([6, 6, 6, 6])

In [10]:
ThisMat[:,3] + 3   #even though I referenced a column, the output is given as a row, it only has 1-dim.

array([3, 4, 5, 6])

In [12]:
ThisMat[:,3] = ThisMat[:,3] + 3
print(ThisMat)

[[0 0 0 3]
 [1 1 1 4]
 [2 2 2 5]
 [3 3 3 6]]


In [14]:
ThisMat[:,3] += 3   #This shortcut works in Python, and it didn't work in Matlab!
print(ThisMat)

[[0 0 0 6]
 [1 1 1 7]
 [2 2 2 8]
 [3 3 3 9]]


One strategy: loop on the rows of `ThisMat`, add `n` to each row

In [16]:
ThisMat = np.zeros((4,4), dtype=int)
for n in range(4):
    ThisMat[n] += n   #shortcut for ThisMat[n] = ThisMat[n] + n
print(ThisMat)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [18]:
ThisMat[1]

array([1, 1, 1, 1])

In [20]:
ThisMat[1,0]

1

Recall: `np.arange` is the numpy array version of `range`

In [34]:
print([0, 1, 2, 3])
np.array([0,1,2,3])

[0, 1, 2, 3]


array([0, 1, 2, 3])

In [36]:
print(range(4))
np.arange(4)  #Still computationally efficient, even though all elements are listed

range(0, 4)


array([0, 1, 2, 3])

Loopless strategy: broadcast using addition, which takes + `np.arange(4)` across the (4,4) array of zeros.

In [42]:
ThatMat = np.zeros((4,4), dtype=int)
print(ThatMat)
ThatMat = ThatMat + np.arange(4)
ThatMat

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [44]:
ThatMat.T    #Transpose of ThatMat. Rows swap to Columns, and vice versa.

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

Alternative approach: Replace every row with `np.arange(4)` with careful slicing, then take the transpose

In [46]:
OurMat = np.zeros((4,4), dtype=int)
OurMat[1] = np.arange(4)
print(OurMat)

[[0 0 0 0]
 [0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [48]:
OurMat = np.zeros((4,4), dtype=int)
OurMat[:] = np.arange(4)  #replace all rows with np.arange(4). The shape broadcasts across the entire array
print(OurMat)
print() #blank line, for spacing the outputs
print(OurMat.T)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


Now what if we wanted to broadcast across the columns instead of the rows? It's possible if we can change the shape of `np.arange(4)` into a column

In [50]:
np.arange(4).T #Does not change with a transpose. This is because there is only one dimension to its shape

array([0, 1, 2, 3])

In [52]:
print(np.arange(4).shape)
print(np.arange(4).ndim)

(4,)
1


There are 2 possible workarounds: Write an array by hand or reshape the array

In [58]:
np.array([[0], [1], [2] ,[3]]) #A little annoying to write, even though it's only 4 entries

array([[0],
       [1],
       [2],
       [3]])

In [60]:
np.array([[0, 1, 2, 3]]).T  #Slightly less annoying, but still hard for longer arrays. Double [[ ]] required for 2-dimensional array and transpose.

array([[0],
       [1],
       [2],
       [3]])

In [62]:
np.arange(4).reshape(4,1)  #Best method overall!

array([[0],
       [1],
       [2],
       [3]])

In [64]:
arr = np.zeros((4,4), dtype=int)
print(arr)
print()
z = np.arange(4).reshape(4,1)
print(z)
arr = arr + z
print()
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0]
 [1]
 [2]
 [3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [70]:
arr[3]

array([3, 3, 3, 3])

In [72]:
arr[3] = [2,10]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

The error basically says "I don't know how to stretch a length 2 array into a length 4 array".

In [74]:
arr[3] = [2,10,2,10]
arr

array([[ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [76]:
arr[0] = 5
arr

array([[ 5,  5,  5,  5],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [82]:
arr[:,0:2] = 99
arr

array([[99, 99,  5,  5],
       [99, 99,  1,  1],
       [99, 99,  2,  2],
       [99, 99,  2, 10]])

The above are examples of something called broadcasting, which we'll see next in lecture.

In [84]:
[1,3,4,7].reshape(4,1)   #lists cannot be reshaped. We need numpy arrays in order to reshape

AttributeError: 'list' object has no attribute 'reshape'

In [86]:
arr.shape

(4, 4)

In [88]:
w = np.array([1,3,4,7])

In [130]:
w.shape

(4,)

In [90]:
w.reshape(2,2)

array([[1, 3],
       [4, 7]])

### Further examples with broadcasting

Below, compare the results of adding `v1 + v2` versus adding  `A1 + A2`

In [2]:
import numpy as np

In [104]:
v1 = np.arange(7).reshape(1,7)
print(v1)
print()
A1 = np.zeros((8,7), dtype = int) + v1
print(A1)

[[0 1 2 3 4 5 6]]

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


In [106]:
v2 = np.arange(8).reshape(8,1)
print(v2)
print()
A2 = np.zeros((8,7), dtype = int) + v2
print(A2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

[[0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7]]


In [98]:
v1+v2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [108]:
A1 + A2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [110]:
v1+v2 == A1 + A2

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [112]:
NewArr = np.arange(1,25).reshape(4,6)
NewArr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

Broadcasting a shape (4,6) array with a shape (1,6) array

In [114]:
NewArr + [[1, 1, 11, 1, 1, 1]]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [116]:
np.array([[1, 1, 11, 1, 1, 1]]).shape

(1, 6)

Broadcasting a shape (4,6) array with a shape (6,) array is only different because of [ ] versus [[ ]]

In [118]:
NewArr + [1, 1, 11, 1, 1, 1]

array([[ 2,  3, 14,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 13],
       [14, 15, 26, 17, 18, 19],
       [20, 21, 32, 23, 24, 25]])

In [12]:
np.array([1, 1, 11, 1, 1, 1]).shape

(6,)

Broadcasting a shape (4,6) array with a shape (4,) array is not possible. Nor with a shape (1,4) array. The dimension of length 4 is in the wrong spot

In [121]:
NewArr + [5 , 9, 0, 9]

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [123]:
NewArr + [[5 , 9, 0, 9]]

ValueError: operands could not be broadcast together with shapes (4,6) (1,4) 

We need a shape (4,1) array to broadcast into a shape (4,6) array. There are two good ways to create this:

In [127]:
vecbroadcast1 = np.array([5, 9, 0, 9]).reshape(-1,1)   #the -1 is replaced with whichever number makes this shape work, depending on number of elts.
print(vecbroadcast1)

[[5]
 [9]
 [0]
 [9]]


In [129]:
print(NewArr)
NewArr + vecbroadcast1

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

In [131]:
NewArr +  [[5], [9], [0], [9]]

array([[ 6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18],
       [28, 29, 30, 31, 32, 33]])

Even More examples

In [14]:
a = np.arange(5).reshape(5,1)
b = np.arange(6).reshape(1,6)
c = np.arange(10,16)

print(a)
print(a.shape)
print()
print(b)
print(b.shape)
print()
print(c)
print(c.shape)
d = 15

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)

[[0 1 2 3 4 5]]
(1, 6)

[10 11 12 13 14 15]
(6,)


In [143]:
TheArr = np.arange(30).reshape(5,6)
print(TheArr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [40]:
print(TheArr + a)
print(TheArr*a)

[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]
 [28 29 30 31 32 33]]
[[  0   0   0   0   0   0]
 [  6   7   8   9  10  11]
 [ 24  26  28  30  32  34]
 [ 54  57  60  63  66  69]
 [ 96 100 104 108 112 116]]


In [48]:
print(TheArr + b)
print(TheArr*b)

[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]]
[[  0   1   4   9  16  25]
 [  0   7  16  27  40  55]
 [  0  13  28  45  64  85]
 [  0  19  40  63  88 115]
 [  0  25  52  81 112 145]]


In [147]:
TheArr[0::2] = c #replace every other row with c
print(TheArr)

[[10 11 12 13 14 15]
 [ 6  7  8  9 10 11]
 [10 11 12 13 14 15]
 [18 19 20 21 22 23]
 [10 11 12 13 14 15]]


In [149]:
TheArr[1:5:2] = TheArr[1:5:2] + b
print(TheArr)

[[10 11 12 13 14 15]
 [ 6  8 10 12 14 16]
 [10 11 12 13 14 15]
 [18 20 22 24 26 28]
 [10 11 12 13 14 15]]


In [163]:
print(TheArr) #before

print()

TheArr[1:5:2] += b #  += is a shortcut for TheArr[1:5:2] = TheArr[1:5:2] + b. We can also use *= and -= as shortcuts.
print(TheArr) #after

[[ 10  11  12  13  14  15]
 [  0   7  22  45  76 115]
 [ 10  11  12  13  14  15]
 [  0  19  46  81 124 175]
 [ 10  11  12  13  14  15]]

[[ 10  11  12  13  14  15]
 [  0   8  24  48  80 120]
 [ 10  11  12  13  14  15]
 [  0  20  48  84 128 180]
 [ 10  11  12  13  14  15]]


## Logic in base Python vs. Logic in NumPy

### General Rules

* In base Python: `and`, `or`, `not`
* In NumPy (and pandas): `&`, `|`, `~`   (note that `!=` is used for not equals)

In [91]:
import numpy as np

In [22]:
rng = np.random.default_rng()
n = 20
arr = rng.integers(-50,51, size=n)
mylist = list(arr)

In [24]:
mylist

[8,
 -27,
 33,
 -18,
 5,
 -38,
 19,
 17,
 14,
 48,
 -12,
 50,
 -14,
 -22,
 -19,
 -6,
 14,
 9,
 -18,
 31]

__Motivating Question:__ Find all entries in `arr` and `mylist` that are strictly between -10 and 10.

In [172]:
mylist < 10    #cannot compare an entire list to an integer. But does this work for an array?

TypeError: '<' not supported between instances of 'list' and 'int'

Let's start with the list. We'll do it with something called "list comprehension".

In [26]:
[x for x in mylist  if x < 10 and x > -10]

[8, 5, -6, 9]

In [28]:
smalllist = []
for x in mylist:
    if x < 10 and x > -10:
        smalllist.append(x)

print(smalllist)

[8, 5, -6, 9]


As an example, notice that if I use `&` there is no error. However, I want to avoid doing this. It won't always work the way you expect.

In [30]:
[x for x in mylist if (x > -10) & (x < 10)]

[8, 5, -6, 9]

For those of you that have seen Math 13, here are some examples of DeMorgan's Law (you don't need to know this for Math 9). Note that these results are the same as the output above.

In [32]:
[x for x in mylist if not((x <= -10) or (x >= 10))]

[8, 5, -6, 9]

In [34]:
[x for x in mylist if not(x <= -10) and not(x >= 10)]

[8, 5, -6, 9]

Now let's compare how we can handle this problem using arrays.

In [36]:
arr

array([  8, -27,  33, -18,   5, -38,  19,  17,  14,  48, -12,  50, -14,
       -22, -19,  -6,  14,   9, -18,  31], dtype=int64)

In [38]:
arr < 10

array([ True,  True, False,  True,  True,  True, False, False, False,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True, False])

Now, let's practice with NumPy arrays.

In [40]:
bool = (arr > -10) & (arr < 10)   #success! It works similar to Matlab
print(bool)

[ True False False False  True False False False False False False False
 False False False  True False  True False False]


This is an example of a boolean array. For each entry of `arr` it returns `True` if the corresponding entry is between -10 and 10, and `False` otherwise.

In [42]:
arr[bool] #again like Matlab! Return the elements corresponding to True indices

array([ 8,  5, -6,  9], dtype=int64)

In [44]:
arr[(arr > -10) & (arr < 10)] 

array([ 8,  5, -6,  9], dtype=int64)

This is an example of boolean indexing.

Below is the same type of negation and DeMorgan's Law we saw with lists

In [47]:
(arr <= -10) | (arr >=10)

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [49]:
~(arr <= -10) | (arr >=10)

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True, False,  True, False, False, False,  True,  True,  True,
       False,  True])

In [51]:
arr[~((arr <= -10) | (arr >= 10))]

array([ 8,  5, -6,  9], dtype=int64)

In [53]:
~(arr <=-10) & ~(arr >=10)

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False])

In [55]:
arr[~(arr <= -10) & ~(arr >= 10)]

array([ 8,  5, -6,  9], dtype=int64)

In [208]:
#Notice we get an error, need & symbol in numpy, the word and does not work.
(arr > -10) and (arr < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Note:** Logical negation uses `~`, while not equals uses `!=`

In [59]:
arr != 3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

## The `axis` keyword argument

__Motivating Question from experimental probability:__ If you roll 4 distinct 6-sided dice, what is the probability that the largest value is 5?

The code below models rolling 4 dice.

In [63]:
import numpy as np

In [65]:
rng = np.random.default_rng()

In [171]:
four_rolls = rng.integers(1,7,size=4)
print(four_rolls)

[5 3 4 4]


In [173]:
np.max(four_rolls)

5

In [175]:
four_rolls.max()

5

Let's start by coding this is the way we're most familiar with.

In [68]:
exp = 10  #number of experiments
s = 0  #number of successes
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:  #if the max of 4 rolls equals 5, all in one line. Can expand this to more lines if it's easier for you.
        s += 1 #shorthand for s = s+1
s/exp    #number of successes / number of experiments is the experimental probability

0.3

for-loops are extremely slow! We'll see that in just a minute. Remember the Jupyter magic `%%timeit` – the `it` means iteration, and it runs the code a number of times and computes average time. This will be too slow for this example, so we'll use `%%time`.

In [190]:
%%time
exp = 10**6
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp

CPU times: total: 21.1 s
Wall time: 21.2 s


0.284409

In [192]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
print(arr)

[[5 3 3 3]
 [2 4 6 4]
 [5 4 2 3]
 [1 2 3 1]
 [6 6 1 2]
 [2 6 4 4]
 [5 6 4 2]
 [4 5 1 1]
 [5 3 1 2]
 [6 1 6 6]]


Here, each row of the array represents an experiment.

The first method I'm going to show you is extremely flexible in that it will work for really any function I want – the drawback is that it will also be quite slow.

In [90]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii 

`axis` simply means the direction I want to do the computation along.

In [85]:
print(arr)

[[6 6 3 4]
 [5 6 6 3]
 [3 4 2 3]
 ...
 [3 4 6 4]
 [2 5 1 2]
 [3 4 5 2]]


In [87]:
np.max(arr)  #Maximum out of all 40 entries

6

In [196]:
np.apply_along_axis(np.max, axis=1, arr=arr)

array([5, 6, 5, 3, 6, 6, 6, 5, 5, 6], dtype=int64)

In [194]:
np.apply_along_axis(np.max, axis=1, arr=arr) == 5

array([ True, False,  True, False, False, False, False,  True,  True,
       False])

Try to predict what will happen when I run the following:

In [198]:
np.apply_along_axis(np.max, axis=0, arr=arr)

array([6, 6, 6, 6], dtype=int64)

In [101]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()   #Recall: Numpy interprets True as 1 and False as 0 in numerical computations

0.3

Now, let's time this with $10^6$ experiments. You might be surprised to see that it's still pretty slow.

In [103]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

CPU times: total: 5.36 s
Wall time: 6.49 s


0.284728

The reason this is slower than we expect is because `np.apply_along_axis` is not optimized for this kind of computation. It has to be flexible enough to work with almost any function we give it. 

Important note: some methods of the numpy package directly also apply to individual arrays. for instance, we can take the max of `arr` with `arr.max` instead of `np.max`

In [110]:
print(arr.max())
print(np.max(arr))

6
6


In [112]:
np.max(arr, axis=1)

array([6, 6, 6, ..., 6, 6, 2], dtype=int64)

In [114]:
arr.max(axis=1)

array([6, 6, 6, ..., 6, 6, 2], dtype=int64)

In [116]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

0.2

In [118]:
#1-Dimensional
(arr.max(axis=1) == 5)

array([False, False,  True, False, False, False,  True, False, False,
       False])

In [124]:
arr.max(axis=1).shape

(10,)

In [120]:
#axis = 0 is the default
(arr.max(axis=1) == 5).mean(axis=0)

0.2

The following throws and error, since the array only has one dimension. We only talk about `axis=1` when there are at least two dimensions.

In [122]:
(arr.max(axis=1) == 5).mean(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [101]:
help(arr.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [130]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

CPU times: total: 46.9 ms
Wall time: 75.6 ms


0.284849

Wow! So fast!

## More on the `axis` keyword argument

![](../images/23.jpg)
![](../images/24.jpg)
![](../images/25.jpg)