In [1]:
import numpy as np

In [2]:
6**4

1296

In [3]:
all_dice = []

for i in range(1,7):
    for j in range(1,7):
        for k in range(1,7):
            for l in range(1,7):
                all_dice.append((i,j,k,l))

In [4]:
len(all_dice)

1296

In [5]:
all_dice[:10] #header of first 10 values

[(1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 1, 4),
 (1, 1, 1, 5),
 (1, 1, 1, 6),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3),
 (1, 1, 2, 4)]

In [6]:
from itertools import product

In [7]:
help(product)

Help on class product in module itertools:

class product(builtins.object)
 |  product(*iterables, repeat=1) --> product object
 |
 |  Cartesian product of input iterables.  Equivalent to nested for-loops.
 |
 |  For example, product(A, B) returns the same as:  ((x,y) for x in A for y in B).
 |  The leftmost iterators are in the outermost for-loop, so the output tuples
 |  cycle in a manner similar to an odometer (with the rightmost element changing
 |  on every iteration).
 |
 |  To compute the product of an iterable with itself, specify the number
 |  of repetitions with the optional repeat keyword argument. For example,
 |  product(A, repeat=4) means the same as product(A, A, A, A).
 |
 |  product('ab', range(3)) --> ('a',0) ('a',1) ('a',2) ('b',0) ('b',1) ('b',2)
 |  product((0,1), (0,1), (0,1)) --> (0,0,0) (0,0,1) (0,1,0) (0,1,1) (1,0,0) ...
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Impl

In [8]:
#let's start with repeat=2 just to see what's going on
list(product(range(1,7),repeat=2))   #same as direct or Cartesian product of A x A, from Math 13

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [9]:
temp_list = list(product(range(1,7),repeat=4))

In [10]:
%%time
temp_list = list(product(range(1,7),repeat=20))

MemoryError: 

In [11]:
list(product(["a","b","c"],[5,6])) #cartesian product

[('a', 5), ('a', 6), ('b', 5), ('b', 6), ('c', 5), ('c', 6)]

In [12]:
list(product(["a","b","c"],["a","b","c"],["a","b","c"]))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [13]:
list(product(["a","b","c"],repeat=3))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [14]:
for x in ["a","b","c"]:
    print(x)

a
b
c


In [15]:
len(temp_list)

1296

In [16]:
arr = np.array(temp_list)

In [17]:
arr[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       [1, 1, 1, 4],
       [1, 1, 1, 5],
       [1, 1, 1, 6],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 1, 2, 3],
       [1, 1, 2, 4]])

In [18]:
arr.shape

(1296, 4)

In [19]:
#here is our exact probability
(arr.max(axis = 1) == 5).mean()

0.2847222222222222

In [20]:
#Mathematically
(5/6)**4 - (4/6)**4

0.2847222222222223

In [21]:
import numpy as np

In [22]:
rng = np.random.default_rng()

In [23]:
rng.random()

0.29167816303009764

In [24]:
arr = rng.random(size=(100,4))

In [25]:
 arr[:7]  #just first 7 rows (rows 0 through 6), instead of all 100 rows

array([[0.99521128, 0.58582263, 0.75087721, 0.82281483],
       [0.1938026 , 0.83012634, 0.73329009, 0.08465543],
       [0.66619988, 0.60580605, 0.77790229, 0.6321901 ],
       [0.47663656, 0.60801846, 0.15025105, 0.22610446],
       [0.85039447, 0.29153558, 0.31896308, 0.06501028],
       [0.91400661, 0.90878507, 0.70983295, 0.80418543],
       [0.15272672, 0.36700807, 0.469224  , 0.76627169]])

In [26]:
arr[:7] > 0.9

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [27]:
(arr[:7] > 0.9).any()

True

In [28]:
(arr[:7] > 0.9).any(axis=1)

array([ True, False, False, False, False,  True, False])

In [29]:
(arr[:7] > 0.9).any(axis=1).sum()

2

In [30]:
arr[:7][(arr[:7] > 0.9).any(axis=1)]

array([[0.99521128, 0.58582263, 0.75087721, 0.82281483],
       [0.91400661, 0.90878507, 0.70983295, 0.80418543]])

In [31]:
comparison = arr > 0.9
comp_rows = comparison.any(axis=1)
arr[comp_rows]

#boolean_rows = (arr > 0.9).any(axis=1)
#arr[boolean_rows]

array([[0.99521128, 0.58582263, 0.75087721, 0.82281483],
       [0.91400661, 0.90878507, 0.70983295, 0.80418543],
       [0.61491385, 0.91920677, 0.07385207, 0.27759299],
       [0.55018503, 0.91416091, 0.43111967, 0.32922177],
       [0.77271055, 0.97482554, 0.02079436, 0.24296981],
       [0.82661329, 0.92324402, 0.33393211, 0.17632084],
       [0.20794642, 0.81538117, 0.96654826, 0.01374897],
       [0.25829071, 0.26284272, 0.95264186, 0.55170218],
       [0.58481209, 0.9134707 , 0.87478582, 0.16814563],
       [0.36192305, 0.17153013, 0.98937213, 0.15307723],
       [0.8116685 , 0.4042865 , 0.92064537, 0.89302198],
       [0.74085665, 0.94472746, 0.5373536 , 0.34172464],
       [0.71713287, 0.56630867, 0.91137599, 0.03335287],
       [0.93498932, 0.77921019, 0.01781765, 0.48707505],
       [0.46634212, 0.47703011, 0.90977883, 0.31697817],
       [0.64489173, 0.49919466, 0.93875711, 0.81201519],
       [0.14656896, 0.98817165, 0.11956614, 0.38927967],
       [0.91477419, 0.1232484 ,

In [32]:
arr = rng.random(size=(100,4))

In [33]:
arr[:7]

array([[0.88916005, 0.56570917, 0.95423653, 0.05230076],
       [0.83413608, 0.80390119, 0.14535847, 0.5849578 ],
       [0.6591786 , 0.63800894, 0.6115271 , 0.48447216],
       [0.88132148, 0.03058417, 0.59385873, 0.7303164 ],
       [0.67076633, 0.97151388, 0.07232789, 0.24725203],
       [0.41209669, 0.53259149, 0.19210336, 0.55521696],
       [0.24647579, 0.29594105, 0.29321644, 0.76552042]])

In [34]:
((arr[:7] < 0.4)|(arr[:7] > 0.6))

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [35]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all()

False

In [36]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)

array([False, False, False, False,  True, False,  True])

In [37]:
arr[:7][((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)]

array([[0.67076633, 0.97151388, 0.07232789, 0.24725203],
       [0.24647579, 0.29594105, 0.29321644, 0.76552042]])

In [38]:
((arr < 0.4)|(arr > 0.6)).all(axis=1).shape

(100,)

In [39]:
arr[((arr < 0.4)|(arr > 0.6)).all(axis=1)]

array([[0.67076633, 0.97151388, 0.07232789, 0.24725203],
       [0.24647579, 0.29594105, 0.29321644, 0.76552042],
       [0.11422271, 0.60888602, 0.35906117, 0.98606275],
       [0.28817765, 0.04980003, 0.31520035, 0.1983962 ],
       [0.27831545, 0.08684903, 0.82711208, 0.27307052],
       [0.84104324, 0.92050812, 0.10592678, 0.36972331],
       [0.07767332, 0.82889437, 0.6257719 , 0.33903847],
       [0.63377671, 0.72596266, 0.83200635, 0.03645102],
       [0.86867336, 0.15283483, 0.63056231, 0.15090385],
       [0.94608625, 0.23800933, 0.17421976, 0.87490022],
       [0.99131595, 0.13607843, 0.30517686, 0.10190785],
       [0.94613284, 0.12493877, 0.05448411, 0.22651801],
       [0.92513163, 0.32937791, 0.89460323, 0.788078  ],
       [0.34118589, 0.1647941 , 0.25652638, 0.25347688],
       [0.39145573, 0.36502053, 0.69717363, 0.70209116],
       [0.32684341, 0.82193878, 0.92975868, 0.14111624],
       [0.73468015, 0.63277136, 0.30062195, 0.0296196 ],
       [0.94036505, 0.34193669,

In [40]:
arr = rng.integers(2,size=(10,4))

In [41]:
arr

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [42]:
#tuple unpacking
m,n = arr.shape

In [43]:
arr.shape

(10, 4)

In [44]:
m

10

In [45]:
n

4

In [46]:
np.arange(n-1,-1,-1)   #get the exponents first. start at n-1 = 3, stop before -1, and count down -1

array([3, 2, 1, 0])

In [47]:
2**np.arange(n-1,-1,-1)

array([8, 4, 2, 1], dtype=int32)

In [48]:
arr

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [49]:
arr*2**np.arange(n-1,-1,-1)    #Broadcast [8, 4, 2, 1] across all rows of arr, with multiplication

array([[8, 4, 0, 0],
       [0, 4, 2, 1],
       [8, 4, 0, 1],
       [0, 0, 0, 0],
       [8, 4, 2, 1],
       [0, 4, 2, 1],
       [8, 4, 0, 0],
       [0, 4, 2, 1],
       [8, 4, 2, 1],
       [0, 0, 2, 0]], dtype=int64)

In [50]:
(arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

array([12,  7, 13,  0, 15,  7, 12,  7, 15,  2], dtype=int64)

In [51]:
def to_bin(arr):
    _,n = arr.shape   #Note the first part of the shape goes unused, so we can use _ to avoid storing the variable
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [52]:
to_bin(arr)

array([12,  7, 13,  0, 15,  7, 12,  7, 15,  2], dtype=int64)

In [53]:
to_bin(np.array([[1,1],[1,0]]))

array([3, 2])

In [54]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [55]:
arr

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [56]:
type(arr)

numpy.ndarray

In [57]:
isinstance(arr,np.ndarray)

True

In [58]:
isinstance(list(arr),np.ndarray)

False

In [59]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [60]:
to_bin("Hello")

TypeError: Input should be a NumPy array.

In [61]:
to_bin(arr)

array([12,  7, 13,  0, 15,  7, 12,  7, 15,  2], dtype=int64)

In [62]:
to_bin([1,2,3])

TypeError: Input should be a NumPy array.

In [63]:
arr == 0

array([[False, False,  True,  True],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [ True,  True, False,  True]])

In [64]:
arr == 1

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False]])

In [65]:
((arr == 0) | (arr == 1))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
#Check if every entry is 0 or 1
((arr == 0) | (arr == 1)).all()

True

In [67]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    if not ((arr == 0) | (arr == 1)).all():
        raise ValueError("All entries should be 0 or 1.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [68]:
arr
arr2 = arr

In [69]:
arr2[5,2] = 6

In [70]:
arr2

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 6, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [71]:
to_bin(arr2)

ValueError: All entries should be 0 or 1.

In [72]:
to_bin(arr)

ValueError: All entries should be 0 or 1.

In [73]:
arr

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 6, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [74]:
arr3 = arr2.copy()

In [75]:
arr3[6,1::2] = 99

In [76]:
arr3

array([[ 1,  1,  0,  0],
       [ 0,  1,  1,  1],
       [ 1,  1,  0,  1],
       [ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 0,  1,  6,  1],
       [ 1, 99,  0, 99],
       [ 0,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 0,  0,  1,  0]], dtype=int64)

In [77]:
arr2

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 6, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 1, 0]], dtype=int64)

In [78]:
mylist = []
for i in range(8):
    mylist.append(7)
mylist

[7, 7, 7, 7, 7, 7, 7, 7]

In [79]:
[7 for _ in range(8)]

[7, 7, 7, 7, 7, 7, 7, 7]

In [80]:
mylist = [-1,4,2,3,-10,2,4]

In [81]:
[x for x in mylist]

[-1, 4, 2, 3, -10, 2, 4]

In [82]:
[x**2 for x in mylist]

[1, 16, 4, 9, 100, 4, 16]

In [83]:
[x for x in mylist if x%2 == 0]

[4, 2, -10, 2, 4]

In [84]:
extralist = []
for x in mylist:
    if x%2 == 0:
        extralist.append(x)
print(extralist)

[4, 2, -10, 2, 4]


In [85]:
mylist

[-1, 4, 2, 3, -10, 2, 4]

In [86]:
[x if x >= 0 else 0 for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [87]:
[0 if x < 0 else x for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [88]:
[[0,1,2] for _ in range(8)]

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [89]:
len([[0,1,2] for _ in range(8)])

8

In [90]:
mylist2 = []
for i in range(8):
    for j in range(3):
        mylist2.append(j)
mylist2

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [91]:
len(mylist2)

24

In [92]:
[j for i in range(8) for j in range(3)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [93]:
s = '''Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.'''

In [94]:
print(s)

Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.


In [95]:
#Notice this goes character by character
[c for c in s]

['I',
 'n',
 't',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 ' ',
 't',
 'o',
 ' ',
 'c',
 'o',
 'm',
 'p',
 'u',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'u',
 's',
 'i',
 'n',
 'g',
 ' ',
 'M',
 'a',
 't',
 'l',
 'a',
 'b',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '.',
 ' ',
 'R',
 'e',
 'p',
 'r',
 'e',
 's',
 'e',
 'n',
 't',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'o',
 'f',
 ' ',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'e',
 'c',
 'i',
 's',
 'i',
 'o',
 'n',
 ',',
 ' ',
 'i',
 'n',
 'p',
 'u',
 't',
 '/',
 'o',
 'u',
 't',
 'p',
 'u',
 't',
 ',',
 ' ',
 'f',
 'u',
 'n',
 'c',
 't',
 'i',
 'o',
 'n',
 's',
 ',',
 ' ',
 'c',
 'u',
 's',
 't',
 'o',
 'm',
 ' ',
 'd',
 'a',
 't',
 'a',
 ' ',
 't',
 'y',
 'p',
 'e',
 's',
 ',',
 ' ',
 't',
 'e',
 's',
 't',
 'i',
 'n',
 'g',
 '/',
 'd',
 'e',
 'b',
 'u',
 'g',
 'g',
 'i'

In [96]:
#This splits the string s at the spaces
wordlist = s.split()
print(wordlist)

['Introduction', 'to', 'computers', 'and', 'programming', 'using', 'Matlab', 'and', 'Python.', 'Representation', 'of', 'numbers', 'and', 'precision,', 'input/output,', 'functions,', 'custom', 'data', 'types,', 'testing/debugging,', 'reading', 'exceptions,', 'plotting', 'data,', 'numerical', 'differentiation,', 'basics', 'of', 'algorithms.', 'Analysis', 'of', 'random', 'processes', 'using', 'computer', 'simulations.']


In [97]:
caplist = [c.capitalize() for c in wordlist]

print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [98]:
caplist = []

for c in wordlist:
    caplist.append(c.capitalize())

In [99]:
print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [100]:
s2 = ' '.join(caplist)

In [101]:
s2

'Introduction To Computers And Programming Using Matlab And Python. Representation Of Numbers And Precision, Input/output, Functions, Custom Data Types, Testing/debugging, Reading Exceptions, Plotting Data, Numerical Differentiation, Basics Of Algorithms. Analysis Of Random Processes Using Computer Simulations.'

In [102]:
type(s2)

str