In [1]:
import numpy as np

In [2]:
6**4

1296

In [3]:
all_dice = []

for i in range(1,7):
    for j in range(1,7):
        for k in range(1,7):
            for l in range(1,7):
                all_dice.append((i,j,k,l))

In [4]:
len(all_dice)

1296

In [5]:
all_dice[:10] #header of first 10 values

[(1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 1, 4),
 (1, 1, 1, 5),
 (1, 1, 1, 6),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3),
 (1, 1, 2, 4)]

In [6]:
from itertools import product

In [7]:
help(product)

Help on class product in module itertools:

class product(builtins.object)
 |  product(*iterables, repeat=1) --> product object
 |
 |  Cartesian product of input iterables.  Equivalent to nested for-loops.
 |
 |  For example, product(A, B) returns the same as:  ((x,y) for x in A for y in B).
 |  The leftmost iterators are in the outermost for-loop, so the output tuples
 |  cycle in a manner similar to an odometer (with the rightmost element changing
 |  on every iteration).
 |
 |  To compute the product of an iterable with itself, specify the number
 |  of repetitions with the optional repeat keyword argument. For example,
 |  product(A, repeat=4) means the same as product(A, A, A, A).
 |
 |  product('ab', range(3)) --> ('a',0) ('a',1) ('a',2) ('b',0) ('b',1) ('b',2)
 |  product((0,1), (0,1), (0,1)) --> (0,0,0) (0,0,1) (0,1,0) (0,1,1) (1,0,0) ...
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Impl

In [8]:
#let's start with repeat=2 just to see what's going on
list(product(range(1,7),repeat=2))   #same as direct or Cartesian product of A x A, from Math 13

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [9]:
temp_list = list(product(range(1,7),repeat=4))

In [10]:
%%time
temp_list = list(product(range(1,7),repeat=20))

MemoryError: 

In [11]:
list(product(["a","b","c"],[5,6])) #cartesian product

[('a', 5), ('a', 6), ('b', 5), ('b', 6), ('c', 5), ('c', 6)]

In [12]:
list(product(["a","b","c"],["a","b","c"],["a","b","c"]))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [13]:
list(product(["a","b","c"],repeat=3))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [14]:
for x in ["a","b","c"]:
    print(x)

a
b
c


In [15]:
len(temp_list)

1296

In [16]:
arr = np.array(temp_list)

In [17]:
arr[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       [1, 1, 1, 4],
       [1, 1, 1, 5],
       [1, 1, 1, 6],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 1, 2, 3],
       [1, 1, 2, 4]])

In [18]:
arr.shape

(1296, 4)

In [19]:
#here is our exact probability
(arr.max(axis = 1) == 5).mean()

0.2847222222222222

In [20]:
#Mathematically
(5/6)**4 - (4/6)**4

0.2847222222222223

In [21]:
import numpy as np

In [22]:
rng = np.random.default_rng()

In [23]:
rng.random()

0.2790125971514549

In [24]:
arr = rng.random(size=(100,4))

In [25]:
 arr[:7]  #just first 7 rows (rows 0 through 6), instead of all 100 rows

array([[0.7038959 , 0.58907178, 0.13194699, 0.40568343],
       [0.80143592, 0.52950341, 0.43124818, 0.89521923],
       [0.80249462, 0.11311416, 0.90128089, 0.93637562],
       [0.37508932, 0.33610446, 0.45149327, 0.59318373],
       [0.99698901, 0.6390701 , 0.7796813 , 0.52066163],
       [0.59816119, 0.68163316, 0.34392369, 0.09381825],
       [0.10363892, 0.39803674, 0.96220565, 0.04775741]])

In [26]:
arr[:7] > 0.9

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [27]:
(arr[:7] > 0.9).any()

True

In [28]:
(arr[:7] > 0.9).any(axis=1)

array([False, False,  True, False,  True, False,  True])

In [29]:
(arr[:7] > 0.9).any(axis=1).sum()

3

In [30]:
arr[:7][(arr[:7] > 0.9).any(axis=1)]

array([[0.80249462, 0.11311416, 0.90128089, 0.93637562],
       [0.99698901, 0.6390701 , 0.7796813 , 0.52066163],
       [0.10363892, 0.39803674, 0.96220565, 0.04775741]])

In [31]:
comparison = arr > 0.9
comp_rows = comparison.any(axis=1)
arr[comp_rows]

#boolean_rows = (arr > 0.9).any(axis=1)
#arr[boolean_rows]

array([[0.80249462, 0.11311416, 0.90128089, 0.93637562],
       [0.99698901, 0.6390701 , 0.7796813 , 0.52066163],
       [0.10363892, 0.39803674, 0.96220565, 0.04775741],
       [0.50537489, 0.98722566, 0.3404874 , 0.03878059],
       [0.3063131 , 0.12379494, 0.94705687, 0.04767393],
       [0.81502115, 0.19536785, 0.83761093, 0.902429  ],
       [0.29776952, 0.84503592, 0.55619206, 0.9618207 ],
       [0.93038111, 0.1592143 , 0.14066681, 0.03549525],
       [0.04680866, 0.33447644, 0.15731423, 0.93864967],
       [0.42161129, 0.28603388, 0.75836615, 0.96199843],
       [0.30245503, 0.83086401, 0.98303711, 0.62318988],
       [0.95457229, 0.30294667, 0.86790377, 0.68733291],
       [0.12379987, 0.45632482, 0.9815192 , 0.22022263],
       [0.29470333, 0.6834823 , 0.97926056, 0.01847195],
       [0.53898683, 0.95118025, 0.23023694, 0.3509187 ],
       [0.34737829, 0.790311  , 0.53065069, 0.99310223],
       [0.90837832, 0.91985537, 0.67749178, 0.88611446],
       [0.59677198, 0.96208528,

In [32]:
arr = rng.random(size=(100,4))

In [33]:
arr[:7]

array([[0.29592787, 0.28404149, 0.70244354, 0.48678681],
       [0.53953746, 0.14523991, 0.27731177, 0.75325084],
       [0.73745931, 0.23897034, 0.47780827, 0.28054723],
       [0.66691993, 0.37777473, 0.59409534, 0.04698217],
       [0.58091697, 0.26421278, 0.12580183, 0.09915199],
       [0.7925376 , 0.6730662 , 0.8851344 , 0.17660885],
       [0.30539836, 0.18700929, 0.13126271, 0.7163109 ]])

In [34]:
((arr[:7] < 0.4)|(arr[:7] > 0.6))

array([[ True,  True,  True, False],
       [False,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all()

False

In [36]:
((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)

array([False, False, False, False, False,  True,  True])

In [37]:
arr[:7][((arr[:7] < 0.4)|(arr[:7] > 0.6)).all(axis=1)]

array([[0.7925376 , 0.6730662 , 0.8851344 , 0.17660885],
       [0.30539836, 0.18700929, 0.13126271, 0.7163109 ]])

In [38]:
((arr < 0.4)|(arr > 0.6)).all(axis=1).shape

(100,)

In [39]:
arr[((arr < 0.4)|(arr > 0.6)).all(axis=1)]

array([[0.7925376 , 0.6730662 , 0.8851344 , 0.17660885],
       [0.30539836, 0.18700929, 0.13126271, 0.7163109 ],
       [0.95839968, 0.62828138, 0.77963994, 0.06041644],
       [0.02346528, 0.90726458, 0.15851202, 0.26822114],
       [0.28885093, 0.93995004, 0.87675814, 0.94931729],
       [0.12709829, 0.8086379 , 0.68992744, 0.27338981],
       [0.6649688 , 0.24558141, 0.32282339, 0.71678218],
       [0.8315324 , 0.90681407, 0.34116539, 0.94511214],
       [0.3988637 , 0.09577049, 0.38902152, 0.26549705],
       [0.12357444, 0.67284862, 0.27607199, 0.16700278],
       [0.65579887, 0.037034  , 0.71197763, 0.11711869],
       [0.21065666, 0.78174303, 0.26302588, 0.1496688 ],
       [0.29654688, 0.65698306, 0.01799045, 0.89405598],
       [0.08073897, 0.63068046, 0.72583056, 0.34919853],
       [0.13016604, 0.32796905, 0.62262134, 0.13755742],
       [0.00273539, 0.32442435, 0.88621635, 0.20780799],
       [0.68888122, 0.77922678, 0.82333851, 0.2721601 ],
       [0.85941978, 0.0397478 ,

In [40]:
arr = rng.integers(2,size=(10,4))

In [41]:
arr

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [42]:
#tuple unpacking
m,n = arr.shape

In [43]:
arr.shape

(10, 4)

In [44]:
m

10

In [45]:
n

4

In [46]:
np.arange(n-1,-1,-1)   #get the exponents first. start at n-1 = 3, stop before -1, and count down -1

array([3, 2, 1, 0])

In [47]:
2**np.arange(n-1,-1,-1)

array([8, 4, 2, 1], dtype=int32)

In [48]:
arr

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [49]:
arr*2**np.arange(n-1,-1,-1)    #Broadcast [8, 4, 2, 1] across all rows of arr, with multiplication

array([[8, 0, 0, 0],
       [0, 0, 2, 0],
       [8, 0, 0, 0],
       [0, 4, 2, 0],
       [0, 4, 0, 1],
       [0, 4, 2, 0],
       [8, 4, 0, 1],
       [8, 0, 2, 0],
       [8, 0, 0, 1],
       [0, 4, 2, 0]], dtype=int64)

In [50]:
(arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

array([ 8,  2,  8,  6,  5,  6, 13, 10,  9,  6], dtype=int64)

In [51]:
def to_bin(arr):
    _,n = arr.shape   #Note the first part of the shape goes unused, so we can use _ to avoid storing the variable
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [52]:
to_bin(arr)

array([ 8,  2,  8,  6,  5,  6, 13, 10,  9,  6], dtype=int64)

In [53]:
to_bin(np.array([[1,1],[1,0]]))

array([3, 2])

In [54]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [55]:
arr

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [56]:
type(arr)

numpy.ndarray

In [57]:
isinstance(arr,np.ndarray)

True

In [58]:
isinstance(list(arr),np.ndarray)

False

In [59]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [60]:
to_bin("Hello")

TypeError: Input should be a NumPy array.

In [61]:
to_bin(arr)

array([ 8,  2,  8,  6,  5,  6, 13, 10,  9,  6], dtype=int64)

In [62]:
to_bin([1,2,3])

TypeError: Input should be a NumPy array.

In [63]:
arr == 0

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [ True, False, False,  True]])

In [64]:
arr == 1

array([[ True, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [65]:
((arr == 0) | (arr == 1))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
#Check if every entry is 0 or 1
((arr == 0) | (arr == 1)).all()

True

In [67]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    if not ((arr == 0) | (arr == 1)).all():
        raise ValueError("All entries should be 0 or 1.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [68]:
arr
arr2 = arr

In [69]:
arr2[5,2] = 6

In [70]:
arr2

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 6, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [71]:
to_bin(arr2)

ValueError: All entries should be 0 or 1.

In [72]:
to_bin(arr)

ValueError: All entries should be 0 or 1.

In [73]:
arr

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 6, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [74]:
arr3 = arr2.copy()

In [75]:
arr3[6,1::2] = 99

In [76]:
arr3

array([[ 1,  0,  0,  0],
       [ 0,  0,  1,  0],
       [ 1,  0,  0,  0],
       [ 0,  1,  1,  0],
       [ 0,  1,  0,  1],
       [ 0,  1,  6,  0],
       [ 1, 99,  0, 99],
       [ 1,  0,  1,  0],
       [ 1,  0,  0,  1],
       [ 0,  1,  1,  0]], dtype=int64)

In [77]:
arr2

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 6, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]], dtype=int64)

In [78]:
mylist = []
for i in range(8):
    mylist.append(7)
mylist

[7, 7, 7, 7, 7, 7, 7, 7]

In [79]:
[7 for _ in range(8)]

[7, 7, 7, 7, 7, 7, 7, 7]

In [80]:
mylist = [-1,4,2,3,-10,2,4]

In [81]:
[x for x in mylist]

[-1, 4, 2, 3, -10, 2, 4]

In [82]:
[x**2 for x in mylist]

[1, 16, 4, 9, 100, 4, 16]

In [83]:
[x for x in mylist if x%2 == 0]

[4, 2, -10, 2, 4]

In [84]:
extralist = []
for x in mylist:
    if x%2 == 0:
        extralist.append(x)
print(extralist)

[4, 2, -10, 2, 4]


In [85]:
mylist

[-1, 4, 2, 3, -10, 2, 4]

In [86]:
[x if x >= 0 else 0 for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [87]:
[0 if x < 0 else x for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [88]:
[[0,1,2] for _ in range(8)]

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [89]:
len([[0,1,2] for _ in range(8)])

8

In [90]:
mylist2 = []
for i in range(8):
    for j in range(3):
        mylist2.append(j)
mylist2

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [91]:
len(mylist2)

24

In [92]:
[j for i in range(8) for j in range(3)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [93]:
s = '''Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.'''

In [94]:
print(s)

Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.


In [95]:
#Notice this goes character by character
[c for c in s]

['I',
 'n',
 't',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 ' ',
 't',
 'o',
 ' ',
 'c',
 'o',
 'm',
 'p',
 'u',
 't',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'u',
 's',
 'i',
 'n',
 'g',
 ' ',
 'M',
 'a',
 't',
 'l',
 'a',
 'b',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '.',
 ' ',
 'R',
 'e',
 'p',
 'r',
 'e',
 's',
 'e',
 'n',
 't',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'o',
 'f',
 ' ',
 'n',
 'u',
 'm',
 'b',
 'e',
 'r',
 's',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'p',
 'r',
 'e',
 'c',
 'i',
 's',
 'i',
 'o',
 'n',
 ',',
 ' ',
 'i',
 'n',
 'p',
 'u',
 't',
 '/',
 'o',
 'u',
 't',
 'p',
 'u',
 't',
 ',',
 ' ',
 'f',
 'u',
 'n',
 'c',
 't',
 'i',
 'o',
 'n',
 's',
 ',',
 ' ',
 'c',
 'u',
 's',
 't',
 'o',
 'm',
 ' ',
 'd',
 'a',
 't',
 'a',
 ' ',
 't',
 'y',
 'p',
 'e',
 's',
 ',',
 ' ',
 't',
 'e',
 's',
 't',
 'i',
 'n',
 'g',
 '/',
 'd',
 'e',
 'b',
 'u',
 'g',
 'g',
 'i'

In [96]:
#This splits the string s at the spaces
wordlist = s.split()
print(wordlist)

['Introduction', 'to', 'computers', 'and', 'programming', 'using', 'Matlab', 'and', 'Python.', 'Representation', 'of', 'numbers', 'and', 'precision,', 'input/output,', 'functions,', 'custom', 'data', 'types,', 'testing/debugging,', 'reading', 'exceptions,', 'plotting', 'data,', 'numerical', 'differentiation,', 'basics', 'of', 'algorithms.', 'Analysis', 'of', 'random', 'processes', 'using', 'computer', 'simulations.']


In [97]:
caplist = [c.capitalize() for c in wordlist]

print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [98]:
caplist = []

for c in wordlist:
    caplist.append(c.capitalize())

In [99]:
print(caplist)

['Introduction', 'To', 'Computers', 'And', 'Programming', 'Using', 'Matlab', 'And', 'Python.', 'Representation', 'Of', 'Numbers', 'And', 'Precision,', 'Input/output,', 'Functions,', 'Custom', 'Data', 'Types,', 'Testing/debugging,', 'Reading', 'Exceptions,', 'Plotting', 'Data,', 'Numerical', 'Differentiation,', 'Basics', 'Of', 'Algorithms.', 'Analysis', 'Of', 'Random', 'Processes', 'Using', 'Computer', 'Simulations.']


In [100]:
s2 = ' '.join(caplist)

In [101]:
s2

'Introduction To Computers And Programming Using Matlab And Python. Representation Of Numbers And Precision, Input/output, Functions, Custom Data Types, Testing/debugging, Reading Exceptions, Plotting Data, Numerical Differentiation, Basics Of Algorithms. Analysis Of Random Processes Using Computer Simulations.'

In [102]:
type(s2)

str